/*
 * Copyright 2010-2018 JetBrains s.r.o. Use of this source code is governed by the Apache 2.0 license
 * that can be found in the license/LICENSE.txt file.
 */

package org.jetbrains.kotlin.idea.navigation;

import com.intellij.testFramework.TestDataPath;
import org.jetbrains.kotlin.test.JUnit3RunnerWithInners;
import org.jetbrains.kotlin.test.KotlinTestUtils;
import org.jetbrains.kotlin.test.TargetBackend;
import org.jetbrains.kotlin.test.TestMetadata;
import org.junit.runner.RunWith;

import java.io.File;
import java.util.regex.Pattern;

/** This class is generated by {@link org.jetbrains.kotlin.generators.tests.TestsPackage}. DO NOT MODIFY MANUALLY */
@SuppressWarnings("all")
@TestMetadata("idea/testData/navigation/gotoSuper")
@TestDataPath("$PROJECT_ROOT")
@RunWith(JUnit3RunnerWithInners.class)
public class GotoSuperTestGenerated extends AbstractGotoSuperTest {
    public void testAllFilesPresentInGotoSuper() throws Exception {
        KotlinTestUtils.assertAllTestsPresentByMetadata(this.getClass(), new File("idea/testData/navigation/gotoSuper"), Pattern.compile("^(.+)\\.test$"), TargetBackend.ANY, false);
    }

    @TestMetadata("BadPositionLambdaParameter.test")
    public void testBadPositionLambdaParameter() throws Exception {
        KotlinTestUtils.runTest("idea/testData/navigation/gotoSuper/BadPositionLambdaParameter.test", this::doTest);
    }

    @TestMetadata("ClassSimple.test")
    public void testClassSimple() throws Exception {
        KotlinTestUtils.runTest("idea/testData/navigation/gotoSuper/ClassSimple.test", this::doTest);
    }

    @TestMetadata("DelegatedFun.test")
    public void testDelegatedFun() throws Exception {
        KotlinTestUtils.runTest("idea/testData/navigation/gotoSuper/DelegatedFun.test", this::doTest);
    }

    @TestMetadata("DelegatedProperty.test")
    public void testDelegatedProperty() throws Exception {
        KotlinTestUtils.runTest("idea/testData/navigation/gotoSuper/DelegatedProperty.test", this::doTest);
    }

    @TestMetadata("FakeOverrideFun.test")
    public void testFakeOverrideFun() throws Exception {
        KotlinTestUtils.runTest("idea/testData/navigation/gotoSuper/FakeOverrideFun.test", this::doTest);
    }

    @TestMetadata("FakeOverrideFunWithMostRelevantImplementation.test")
    public void testFakeOverrideFunWithMostRelevantImplementation() throws Exception {
        KotlinTestUtils.runTest("idea/testData/navigation/gotoSuper/FakeOverrideFunWithMostRelevantImplementation.test", this::doTest);
    }

    @TestMetadata("FakeOverrideProperty.test")
    public void testFakeOverrideProperty() throws Exception {
        KotlinTestUtils.runTest("idea/testData/navigation/gotoSuper/FakeOverrideProperty.test", this::doTest);
    }

    @TestMetadata("FunctionSimple.test")
    public void testFunctionSimple() throws Exception {
        KotlinTestUtils.runTest("idea/testData/navigation/gotoSuper/FunctionSimple.test", this::doTest);
    }

    @TestMetadata("ObjectSimple.test")
    public void testObjectSimple() throws Exception {
        KotlinTestUtils.runTest("idea/testData/navigation/gotoSuper/ObjectSimple.test", this::doTest);
    }

    @TestMetadata("PropertySimple.test")
    public void testPropertySimple() throws Exception {
        KotlinTestUtils.runTest("idea/testData/navigation/gotoSuper/PropertySimple.test", this::doTest);
    }

    @TestMetadata("SuperWithNativeToGenericMapping.test")
    public void testSuperWithNativeToGenericMapping() throws Exception {
        KotlinTestUtils.runTest("idea/testData/navigation/gotoSuper/SuperWithNativeToGenericMapping.test", this::doTest);
    }

    @TestMetadata("TraitSimple.test")
    public void testTraitSimple() throws Exception {
        KotlinTestUtils.runTest("idea/testData/navigation/gotoSuper/TraitSimple.test", this::doTest);
    }

    @TestMetadata("TypeAliasInSuperType.test")
    public void testTypeAliasInSuperType() throws Exception {
        KotlinTestUtils.runTest("idea/testData/navigation/gotoSuper/TypeAliasInSuperType.test", this::doTest);
    }
}
