/*
 * Copyright 2010-2018 JetBrains s.r.o. Use of this source code is governed by the Apache 2.0 license
 * that can be found in the license/LICENSE.txt file.
 */

package org.jetbrains.kotlin.idea.navigation;

import com.intellij.testFramework.TestDataPath;
import org.jetbrains.kotlin.test.JUnit3RunnerWithInners;
import org.jetbrains.kotlin.test.KotlinTestUtils;
import org.jetbrains.kotlin.test.TargetBackend;
import org.jetbrains.kotlin.test.TestMetadata;
import org.junit.runner.RunWith;

import java.io.File;
import java.util.regex.Pattern;

/** This class is generated by {@link org.jetbrains.kotlin.generators.tests.TestsPackage}. DO NOT MODIFY MANUALLY */
@SuppressWarnings("all")
@TestMetadata("idea/testData/navigation/gotoSuper/multiModule")
@TestDataPath("$PROJECT_ROOT")
@RunWith(JUnit3RunnerWithInners.class)
public class KotlinGotoSuperMultiModuleTestGenerated extends AbstractKotlinGotoSuperMultiModuleTest {
    @TestMetadata("actualClass")
    public void testActualClass() throws Exception {
        KotlinTestUtils.runTest("idea/testData/navigation/gotoSuper/multiModule/actualClass/", this::doTest);
    }

    @TestMetadata("actualFunction")
    public void testActualFunction() throws Exception {
        KotlinTestUtils.runTest("idea/testData/navigation/gotoSuper/multiModule/actualFunction/", this::doTest);
    }

    @TestMetadata("actualProperty")
    public void testActualProperty() throws Exception {
        KotlinTestUtils.runTest("idea/testData/navigation/gotoSuper/multiModule/actualProperty/", this::doTest);
    }

    public void testAllFilesPresentInMultiModule() throws Exception {
        KotlinTestUtils.assertAllTestsPresentByMetadata(this.getClass(), new File("idea/testData/navigation/gotoSuper/multiModule"), Pattern.compile("^([^\\.]+)$"), TargetBackend.ANY, false);
    }
}
