/*
 * Copyright 2010-2018 JetBrains s.r.o. Use of this source code is governed by the Apache 2.0 license
 * that can be found in the license/LICENSE.txt file.
 */

package org.jetbrains.kotlin.idea.resolve;

import com.intellij.testFramework.TestDataPath;
import org.jetbrains.kotlin.test.JUnit3RunnerWithInners;
import org.jetbrains.kotlin.test.KotlinTestUtils;
import org.jetbrains.kotlin.test.TargetBackend;
import org.jetbrains.kotlin.test.TestMetadata;
import org.junit.runner.RunWith;

import java.io.File;
import java.util.regex.Pattern;

/** This class is generated by {@link org.jetbrains.kotlin.generators.tests.TestsPackage}. DO NOT MODIFY MANUALLY */
@SuppressWarnings("all")
@TestMetadata("idea/testData/resolve/referenceWithLib")
@TestDataPath("$PROJECT_ROOT")
@RunWith(JUnit3RunnerWithInners.class)
public class ReferenceResolveWithLibTestGenerated extends AbstractReferenceResolveWithLibTest {
    public void testAllFilesPresentInReferenceWithLib() throws Exception {
        KotlinTestUtils.assertAllTestsPresentByMetadata(this.getClass(), new File("idea/testData/resolve/referenceWithLib"), Pattern.compile("^(.+)\\.kt$"), TargetBackend.ANY, false);
    }

    @TestMetadata("delegatedPropertyWithTypeParameters.kt")
    public void testDelegatedPropertyWithTypeParameters() throws Exception {
        KotlinTestUtils.runTest("idea/testData/resolve/referenceWithLib/delegatedPropertyWithTypeParameters.kt", this::doTest);
    }

    @TestMetadata("fakeOverride.kt")
    public void testFakeOverride() throws Exception {
        KotlinTestUtils.runTest("idea/testData/resolve/referenceWithLib/fakeOverride.kt", this::doTest);
    }

    @TestMetadata("fakeOverride2.kt")
    public void testFakeOverride2() throws Exception {
        KotlinTestUtils.runTest("idea/testData/resolve/referenceWithLib/fakeOverride2.kt", this::doTest);
    }

    @TestMetadata("innerClassFromLib.kt")
    public void testInnerClassFromLib() throws Exception {
        KotlinTestUtils.runTest("idea/testData/resolve/referenceWithLib/innerClassFromLib.kt", this::doTest);
    }

    @TestMetadata("iteratorWithTypeParameter.kt")
    public void testIteratorWithTypeParameter() throws Exception {
        KotlinTestUtils.runTest("idea/testData/resolve/referenceWithLib/iteratorWithTypeParameter.kt", this::doTest);
    }

    @TestMetadata("multiDeclarationWithTypeParameters.kt")
    public void testMultiDeclarationWithTypeParameters() throws Exception {
        KotlinTestUtils.runTest("idea/testData/resolve/referenceWithLib/multiDeclarationWithTypeParameters.kt", this::doTest);
    }

    @TestMetadata("nestedClassFromLib.kt")
    public void testNestedClassFromLib() throws Exception {
        KotlinTestUtils.runTest("idea/testData/resolve/referenceWithLib/nestedClassFromLib.kt", this::doTest);
    }

    @TestMetadata("overloadFun.kt")
    public void testOverloadFun() throws Exception {
        KotlinTestUtils.runTest("idea/testData/resolve/referenceWithLib/overloadFun.kt", this::doTest);
    }

    @TestMetadata("overridingFunctionWithSamAdapter.kt")
    public void testOverridingFunctionWithSamAdapter() throws Exception {
        KotlinTestUtils.runTest("idea/testData/resolve/referenceWithLib/overridingFunctionWithSamAdapter.kt", this::doTest);
    }

    @TestMetadata("packageOfLibDeclaration.kt")
    public void testPackageOfLibDeclaration() throws Exception {
        KotlinTestUtils.runTest("idea/testData/resolve/referenceWithLib/packageOfLibDeclaration.kt", this::doTest);
    }

    @TestMetadata("referenceToRootJavaClassFromLib.kt")
    public void testReferenceToRootJavaClassFromLib() throws Exception {
        KotlinTestUtils.runTest("idea/testData/resolve/referenceWithLib/referenceToRootJavaClassFromLib.kt", this::doTest);
    }

    @TestMetadata("sameNameInLib.kt")
    public void testSameNameInLib() throws Exception {
        KotlinTestUtils.runTest("idea/testData/resolve/referenceWithLib/sameNameInLib.kt", this::doTest);
    }

    @TestMetadata("setWithTypeParameters.kt")
    public void testSetWithTypeParameters() throws Exception {
        KotlinTestUtils.runTest("idea/testData/resolve/referenceWithLib/setWithTypeParameters.kt", this::doTest);
    }
}
