/*
 * Copyright 2010-2018 JetBrains s.r.o. Use of this source code is governed by the Apache 2.0 license
 * that can be found in the license/LICENSE.txt file.
 */

package org.jetbrains.kotlin.idea.debugger.evaluate;

import com.intellij.testFramework.TestDataPath;
import org.jetbrains.kotlin.test.JUnit3RunnerWithInners;
import org.jetbrains.kotlin.test.KotlinTestUtils;
import org.jetbrains.kotlin.test.TargetBackend;
import org.jetbrains.kotlin.test.TestMetadata;
import org.junit.runner.RunWith;

import java.io.File;
import java.util.regex.Pattern;

/** This class is generated by {@link org.jetbrains.kotlin.generators.tests.TestsPackage}. DO NOT MODIFY MANUALLY */
@SuppressWarnings("all")
@TestMetadata("idea/idea-completion/testData/basic/codeFragments")
@TestDataPath("$PROJECT_ROOT")
@RunWith(JUnit3RunnerWithInners.class)
public class CodeFragmentCompletionTestGenerated extends AbstractCodeFragmentCompletionTest {
    public void testAllFilesPresentInCodeFragments() throws Exception {
        KotlinTestUtils.assertAllTestsPresentByMetadata(this.getClass(), new File("idea/idea-completion/testData/basic/codeFragments"), Pattern.compile("^(.+)\\.kt$"), TargetBackend.ANY, true);
    }

    @TestMetadata("blockCodeFragment.kt")
    public void testBlockCodeFragment() throws Exception {
        KotlinTestUtils.runTest("idea/idea-completion/testData/basic/codeFragments/blockCodeFragment.kt", this::doTest);
    }

    @TestMetadata("classHeader.kt")
    public void testClassHeader() throws Exception {
        KotlinTestUtils.runTest("idea/idea-completion/testData/basic/codeFragments/classHeader.kt", this::doTest);
    }

    @TestMetadata("elementAt.kt")
    public void testElementAt() throws Exception {
        KotlinTestUtils.runTest("idea/idea-completion/testData/basic/codeFragments/elementAt.kt", this::doTest);
    }

    @TestMetadata("elementAtFirstInBlock.kt")
    public void testElementAtFirstInBlock() throws Exception {
        KotlinTestUtils.runTest("idea/idea-completion/testData/basic/codeFragments/elementAtFirstInBlock.kt", this::doTest);
    }

    @TestMetadata("localVal.kt")
    public void testLocalVal() throws Exception {
        KotlinTestUtils.runTest("idea/idea-completion/testData/basic/codeFragments/localVal.kt", this::doTest);
    }

    @TestMetadata("localVariables.kt")
    public void testLocalVariables() throws Exception {
        KotlinTestUtils.runTest("idea/idea-completion/testData/basic/codeFragments/localVariables.kt", this::doTest);
    }

    @TestMetadata("localVariablesOnReturn.kt")
    public void testLocalVariablesOnReturn() throws Exception {
        KotlinTestUtils.runTest("idea/idea-completion/testData/basic/codeFragments/localVariablesOnReturn.kt", this::doTest);
    }

    @TestMetadata("noDuplicatesForSyntheticProperties.kt")
    public void testNoDuplicatesForSyntheticProperties() throws Exception {
        KotlinTestUtils.runTest("idea/idea-completion/testData/basic/codeFragments/noDuplicatesForSyntheticProperties.kt", this::doTest);
    }

    @TestMetadata("privatesInSecondPressCompletion.kt")
    public void testPrivatesInSecondPressCompletion() throws Exception {
        KotlinTestUtils.runTest("idea/idea-completion/testData/basic/codeFragments/privatesInSecondPressCompletion.kt", this::doTest);
    }

    @TestMetadata("topLevel.kt")
    public void testTopLevel() throws Exception {
        KotlinTestUtils.runTest("idea/idea-completion/testData/basic/codeFragments/topLevel.kt", this::doTest);
    }

    @TestMetadata("idea/idea-completion/testData/basic/codeFragments/runtimeType")
    @TestDataPath("$PROJECT_ROOT")
    @RunWith(JUnit3RunnerWithInners.class)
    public static class RuntimeType extends AbstractCodeFragmentCompletionTest {
        public void testAllFilesPresentInRuntimeType() throws Exception {
            KotlinTestUtils.assertAllTestsPresentByMetadata(this.getClass(), new File("idea/idea-completion/testData/basic/codeFragments/runtimeType"), Pattern.compile("^(.+)\\.kt$"), TargetBackend.ANY, true);
        }

        @TestMetadata("castWithGenerics.kt")
        public void testCastWithGenerics() throws Exception {
            KotlinTestUtils.runTest("idea/idea-completion/testData/basic/codeFragments/runtimeType/castWithGenerics.kt", this::doTest);
        }

        @TestMetadata("complexHierarchy.kt")
        public void testComplexHierarchy() throws Exception {
            KotlinTestUtils.runTest("idea/idea-completion/testData/basic/codeFragments/runtimeType/complexHierarchy.kt", this::doTest);
        }

        @TestMetadata("extensionMethod.kt")
        public void testExtensionMethod() throws Exception {
            KotlinTestUtils.runTest("idea/idea-completion/testData/basic/codeFragments/runtimeType/extensionMethod.kt", this::doTest);
        }

        @TestMetadata("notImportedExtension.kt")
        public void testNotImportedExtension() throws Exception {
            KotlinTestUtils.runTest("idea/idea-completion/testData/basic/codeFragments/runtimeType/notImportedExtension.kt", this::doTest);
        }

        @TestMetadata("runtimeCast.kt")
        public void testRuntimeCast() throws Exception {
            KotlinTestUtils.runTest("idea/idea-completion/testData/basic/codeFragments/runtimeType/runtimeCast.kt", this::doTest);
        }

        @TestMetadata("smartCompletion.kt")
        public void testSmartCompletion() throws Exception {
            KotlinTestUtils.runTest("idea/idea-completion/testData/basic/codeFragments/runtimeType/smartCompletion.kt", this::doTest);
        }
    }
}
