/*
 * Copyright 2010-2018 JetBrains s.r.o. Use of this source code is governed by the Apache 2.0 license
 * that can be found in the license/LICENSE.txt file.
 */

package org.jetbrains.kotlin.idea.debugger.evaluate;

import com.intellij.testFramework.TestDataPath;
import org.jetbrains.kotlin.test.JUnit3RunnerWithInners;
import org.jetbrains.kotlin.test.KotlinTestUtils;
import org.jetbrains.kotlin.test.TargetBackend;
import org.jetbrains.kotlin.test.TestMetadata;
import org.junit.runner.RunWith;

import java.io.File;
import java.util.regex.Pattern;

/** This class is generated by {@link org.jetbrains.kotlin.generators.tests.TestsPackage}. DO NOT MODIFY MANUALLY */
@SuppressWarnings("all")
@RunWith(JUnit3RunnerWithInners.class)
public class CodeFragmentHighlightingTestGenerated extends AbstractCodeFragmentHighlightingTest {
    @TestMetadata("idea/testData/checker/codeFragments")
    @TestDataPath("$PROJECT_ROOT")
    @RunWith(JUnit3RunnerWithInners.class)
    public static class CodeFragments extends AbstractCodeFragmentHighlightingTest {
        public void testAllFilesPresentInCodeFragments() throws Exception {
            KotlinTestUtils.assertAllTestsPresentByMetadata(this.getClass(), new File("idea/testData/checker/codeFragments"), Pattern.compile("^(.+)\\.kt$"), TargetBackend.ANY, false);
        }

        @TestMetadata("anonymousObject.kt")
        public void testAnonymousObject() throws Exception {
            KotlinTestUtils.runTest("idea/testData/checker/codeFragments/anonymousObject.kt", this::doTest);
        }

        @TestMetadata("binaryExpression.kt")
        public void testBinaryExpression() throws Exception {
            KotlinTestUtils.runTest("idea/testData/checker/codeFragments/binaryExpression.kt", this::doTest);
        }

        @TestMetadata("blockCodeFragment.kt")
        public void testBlockCodeFragment() throws Exception {
            KotlinTestUtils.runTest("idea/testData/checker/codeFragments/blockCodeFragment.kt", this::doTest);
        }

        @TestMetadata("callExpression.kt")
        public void testCallExpression() throws Exception {
            KotlinTestUtils.runTest("idea/testData/checker/codeFragments/callExpression.kt", this::doTest);
        }

        @TestMetadata("classHeader.kt")
        public void testClassHeader() throws Exception {
            KotlinTestUtils.runTest("idea/testData/checker/codeFragments/classHeader.kt", this::doTest);
        }

        @TestMetadata("classHeaderWithTypeArguments.kt")
        public void testClassHeaderWithTypeArguments() throws Exception {
            KotlinTestUtils.runTest("idea/testData/checker/codeFragments/classHeaderWithTypeArguments.kt", this::doTest);
        }

        @TestMetadata("contextElementAsStatement.kt")
        public void testContextElementAsStatement() throws Exception {
            KotlinTestUtils.runTest("idea/testData/checker/codeFragments/contextElementAsStatement.kt", this::doTest);
        }

        @TestMetadata("elementAtIfWithoutBraces.kt")
        public void testElementAtIfWithoutBraces() throws Exception {
            KotlinTestUtils.runTest("idea/testData/checker/codeFragments/elementAtIfWithoutBraces.kt", this::doTest);
        }

        @TestMetadata("elementAtWhenBranch.kt")
        public void testElementAtWhenBranch() throws Exception {
            KotlinTestUtils.runTest("idea/testData/checker/codeFragments/elementAtWhenBranch.kt", this::doTest);
        }

        @TestMetadata("localVariables.kt")
        public void testLocalVariables() throws Exception {
            KotlinTestUtils.runTest("idea/testData/checker/codeFragments/localVariables.kt", this::doTest);
        }

        @TestMetadata("localVariablesOnReturn.kt")
        public void testLocalVariablesOnReturn() throws Exception {
            KotlinTestUtils.runTest("idea/testData/checker/codeFragments/localVariablesOnReturn.kt", this::doTest);
        }

        @TestMetadata("primaryConstructor.kt")
        public void testPrimaryConstructor() throws Exception {
            KotlinTestUtils.runTest("idea/testData/checker/codeFragments/primaryConstructor.kt", this::doTest);
        }

        @TestMetadata("primaryConstructorLocal.kt")
        public void testPrimaryConstructorLocal() throws Exception {
            KotlinTestUtils.runTest("idea/testData/checker/codeFragments/primaryConstructorLocal.kt", this::doTest);
        }

        @TestMetadata("privateFunArgumentsResolve.kt")
        public void testPrivateFunArgumentsResolve() throws Exception {
            KotlinTestUtils.runTest("idea/testData/checker/codeFragments/privateFunArgumentsResolve.kt", this::doTest);
        }

        @TestMetadata("privateFunTypeArguments.kt")
        public void testPrivateFunTypeArguments() throws Exception {
            KotlinTestUtils.runTest("idea/testData/checker/codeFragments/privateFunTypeArguments.kt", this::doTest);
        }

        @TestMetadata("privateMember.kt")
        public void testPrivateMember() throws Exception {
            KotlinTestUtils.runTest("idea/testData/checker/codeFragments/privateMember.kt", this::doTest);
        }

        @TestMetadata("protectedMember.kt")
        public void testProtectedMember() throws Exception {
            KotlinTestUtils.runTest("idea/testData/checker/codeFragments/protectedMember.kt", this::doTest);
        }

        @TestMetadata("secondaryConstructor.kt")
        public void testSecondaryConstructor() throws Exception {
            KotlinTestUtils.runTest("idea/testData/checker/codeFragments/secondaryConstructor.kt", this::doTest);
        }

        @TestMetadata("secondaryConstructorWithoutBraces.kt")
        public void testSecondaryConstructorWithoutBraces() throws Exception {
            KotlinTestUtils.runTest("idea/testData/checker/codeFragments/secondaryConstructorWithoutBraces.kt", this::doTest);
        }

        @TestMetadata("simpleNameExpression.kt")
        public void testSimpleNameExpression() throws Exception {
            KotlinTestUtils.runTest("idea/testData/checker/codeFragments/simpleNameExpression.kt", this::doTest);
        }

        @TestMetadata("smartCasts.kt")
        public void testSmartCasts() throws Exception {
            KotlinTestUtils.runTest("idea/testData/checker/codeFragments/smartCasts.kt", this::doTest);
        }

        @TestMetadata("startingFromReturn.kt")
        public void testStartingFromReturn() throws Exception {
            KotlinTestUtils.runTest("idea/testData/checker/codeFragments/startingFromReturn.kt", this::doTest);
        }

        @TestMetadata("withoutBodyFunction.kt")
        public void testWithoutBodyFunction() throws Exception {
            KotlinTestUtils.runTest("idea/testData/checker/codeFragments/withoutBodyFunction.kt", this::doTest);
        }

        @TestMetadata("withoutBodyProperty.kt")
        public void testWithoutBodyProperty() throws Exception {
            KotlinTestUtils.runTest("idea/testData/checker/codeFragments/withoutBodyProperty.kt", this::doTest);
        }
    }

    @TestMetadata("idea/testData/checker/codeFragments/imports")
    @TestDataPath("$PROJECT_ROOT")
    @RunWith(JUnit3RunnerWithInners.class)
    public static class Imports extends AbstractCodeFragmentHighlightingTest {
        public void testAllFilesPresentInImports() throws Exception {
            KotlinTestUtils.assertAllTestsPresentByMetadata(this.getClass(), new File("idea/testData/checker/codeFragments/imports"), Pattern.compile("^(.+)\\.kt$"), TargetBackend.ANY, true);
        }

        @TestMetadata("hashMap.kt")
        public void testHashMap() throws Exception {
            KotlinTestUtils.runTest("idea/testData/checker/codeFragments/imports/hashMap.kt", this::doTestWithImport);
        }
    }
}
