/*
 * Copyright 2010-2018 JetBrains s.r.o. Use of this source code is governed by the Apache 2.0 license
 * that can be found in the license/LICENSE.txt file.
 */

package org.jetbrains.kotlin.ir;

import com.intellij.testFramework.TestDataPath;
import org.jetbrains.kotlin.test.JUnit3RunnerWithInners;
import org.jetbrains.kotlin.test.KotlinTestUtils;
import org.jetbrains.kotlin.test.TargetBackend;
import org.jetbrains.kotlin.test.TestMetadata;
import org.junit.runner.RunWith;

import java.io.File;
import java.util.regex.Pattern;

/** This class is generated by {@link org.jetbrains.kotlin.generators.tests.TestsPackage}. DO NOT MODIFY MANUALLY */
@SuppressWarnings("all")
@TestMetadata("compiler/testData/ir/irText")
@TestDataPath("$PROJECT_ROOT")
@RunWith(JUnit3RunnerWithInners.class)
public class IrTextTestCaseGenerated extends AbstractIrTextTestCase {
    public void testAllFilesPresentInIrText() throws Exception {
        KotlinTestUtils.assertAllTestsPresentByMetadata(this.getClass(), new File("compiler/testData/ir/irText"), Pattern.compile("^(.+)\\.kt$"), TargetBackend.ANY, true);
    }

    @TestMetadata("compiler/testData/ir/irText/classes")
    @TestDataPath("$PROJECT_ROOT")
    @RunWith(JUnit3RunnerWithInners.class)
    public static class Classes extends AbstractIrTextTestCase {
        @TestMetadata("abstractMembers.kt")
        public void testAbstractMembers() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/ir/irText/classes/abstractMembers.kt", this::doTest);
        }

        public void testAllFilesPresentInClasses() throws Exception {
            KotlinTestUtils.assertAllTestsPresentByMetadata(this.getClass(), new File("compiler/testData/ir/irText/classes"), Pattern.compile("^(.+)\\.kt$"), TargetBackend.ANY, true);
        }

        @TestMetadata("annotationClasses.kt")
        public void testAnnotationClasses() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/ir/irText/classes/annotationClasses.kt", this::doTest);
        }

        @TestMetadata("argumentReorderingInDelegatingConstructorCall.kt")
        public void testArgumentReorderingInDelegatingConstructorCall() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/ir/irText/classes/argumentReorderingInDelegatingConstructorCall.kt", this::doTest);
        }

        @TestMetadata("classMembers.kt")
        public void testClassMembers() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/ir/irText/classes/classMembers.kt", this::doTest);
        }

        @TestMetadata("classes.kt")
        public void testClasses() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/ir/irText/classes/classes.kt", this::doTest);
        }

        @TestMetadata("companionObject.kt")
        public void testCompanionObject() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/ir/irText/classes/companionObject.kt", this::doTest);
        }

        @TestMetadata("dataClassWithArrayMembers.kt")
        public void testDataClassWithArrayMembers() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/ir/irText/classes/dataClassWithArrayMembers.kt", this::doTest);
        }

        @TestMetadata("dataClasses.kt")
        public void testDataClasses() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/ir/irText/classes/dataClasses.kt", this::doTest);
        }

        @TestMetadata("dataClassesGeneric.kt")
        public void testDataClassesGeneric() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/ir/irText/classes/dataClassesGeneric.kt", this::doTest);
        }

        @TestMetadata("delegatedImplementation.kt")
        public void testDelegatedImplementation() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/ir/irText/classes/delegatedImplementation.kt", this::doTest);
        }

        @TestMetadata("delegatedImplementationWithExplicitOverride.kt")
        public void testDelegatedImplementationWithExplicitOverride() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/ir/irText/classes/delegatedImplementationWithExplicitOverride.kt", this::doTest);
        }

        @TestMetadata("delegatingConstructorCallToTypeAliasConstructor.kt")
        public void testDelegatingConstructorCallToTypeAliasConstructor() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/ir/irText/classes/delegatingConstructorCallToTypeAliasConstructor.kt", this::doTest);
        }

        @TestMetadata("delegatingConstructorCallsInSecondaryConstructors.kt")
        public void testDelegatingConstructorCallsInSecondaryConstructors() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/ir/irText/classes/delegatingConstructorCallsInSecondaryConstructors.kt", this::doTest);
        }

        @TestMetadata("enum.kt")
        public void testEnum() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/ir/irText/classes/enum.kt", this::doTest);
        }

        @TestMetadata("enumWithSecondaryCtor.kt")
        public void testEnumWithSecondaryCtor() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/ir/irText/classes/enumWithSecondaryCtor.kt", this::doTest);
        }

        @TestMetadata("initBlock.kt")
        public void testInitBlock() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/ir/irText/classes/initBlock.kt", this::doTest);
        }

        @TestMetadata("initVal.kt")
        public void testInitVal() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/ir/irText/classes/initVal.kt", this::doTest);
        }

        @TestMetadata("initVar.kt")
        public void testInitVar() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/ir/irText/classes/initVar.kt", this::doTest);
        }

        @TestMetadata("innerClass.kt")
        public void testInnerClass() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/ir/irText/classes/innerClass.kt", this::doTest);
        }

        @TestMetadata("innerClassWithDelegatingConstructor.kt")
        public void testInnerClassWithDelegatingConstructor() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/ir/irText/classes/innerClassWithDelegatingConstructor.kt", this::doTest);
        }

        @TestMetadata("lambdaInDataClassDefaultParameter.kt")
        public void testLambdaInDataClassDefaultParameter() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/ir/irText/classes/lambdaInDataClassDefaultParameter.kt", this::doTest);
        }

        @TestMetadata("localClasses.kt")
        public void testLocalClasses() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/ir/irText/classes/localClasses.kt", this::doTest);
        }

        @TestMetadata("objectLiteralExpressions.kt")
        public void testObjectLiteralExpressions() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/ir/irText/classes/objectLiteralExpressions.kt", this::doTest);
        }

        @TestMetadata("objectWithInitializers.kt")
        public void testObjectWithInitializers() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/ir/irText/classes/objectWithInitializers.kt", this::doTest);
        }

        @TestMetadata("outerClassAccess.kt")
        public void testOuterClassAccess() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/ir/irText/classes/outerClassAccess.kt", this::doTest);
        }

        @TestMetadata("primaryConstructor.kt")
        public void testPrimaryConstructor() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/ir/irText/classes/primaryConstructor.kt", this::doTest);
        }

        @TestMetadata("primaryConstructorWithSuperConstructorCall.kt")
        public void testPrimaryConstructorWithSuperConstructorCall() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/ir/irText/classes/primaryConstructorWithSuperConstructorCall.kt", this::doTest);
        }

        @TestMetadata("qualifiedSuperCalls.kt")
        public void testQualifiedSuperCalls() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/ir/irText/classes/qualifiedSuperCalls.kt", this::doTest);
        }

        @TestMetadata("sealedClasses.kt")
        public void testSealedClasses() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/ir/irText/classes/sealedClasses.kt", this::doTest);
        }

        @TestMetadata("secondaryConstructorWithInitializersFromClassBody.kt")
        public void testSecondaryConstructorWithInitializersFromClassBody() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/ir/irText/classes/secondaryConstructorWithInitializersFromClassBody.kt", this::doTest);
        }

        @TestMetadata("secondaryConstructors.kt")
        public void testSecondaryConstructors() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/ir/irText/classes/secondaryConstructors.kt", this::doTest);
        }

        @TestMetadata("superCalls.kt")
        public void testSuperCalls() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/ir/irText/classes/superCalls.kt", this::doTest);
        }
    }

    @TestMetadata("compiler/testData/ir/irText/declarations")
    @TestDataPath("$PROJECT_ROOT")
    @RunWith(JUnit3RunnerWithInners.class)
    public static class Declarations extends AbstractIrTextTestCase {
        public void testAllFilesPresentInDeclarations() throws Exception {
            KotlinTestUtils.assertAllTestsPresentByMetadata(this.getClass(), new File("compiler/testData/ir/irText/declarations"), Pattern.compile("^(.+)\\.kt$"), TargetBackend.ANY, true);
        }

        @TestMetadata("catchParameterInTopLevelProperty.kt")
        public void testCatchParameterInTopLevelProperty() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/ir/irText/declarations/catchParameterInTopLevelProperty.kt", this::doTest);
        }

        @TestMetadata("classLevelProperties.kt")
        public void testClassLevelProperties() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/ir/irText/declarations/classLevelProperties.kt", this::doTest);
        }

        @TestMetadata("defaultArguments.kt")
        public void testDefaultArguments() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/ir/irText/declarations/defaultArguments.kt", this::doTest);
        }

        @TestMetadata("delegatedProperties.kt")
        public void testDelegatedProperties() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/ir/irText/declarations/delegatedProperties.kt", this::doTest);
        }

        @TestMetadata("extensionProperties.kt")
        public void testExtensionProperties() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/ir/irText/declarations/extensionProperties.kt", this::doTest);
        }

        @TestMetadata("fakeOverrides.kt")
        public void testFakeOverrides() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/ir/irText/declarations/fakeOverrides.kt", this::doTest);
        }

        @TestMetadata("fileWithAnnotations.kt")
        public void testFileWithAnnotations() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/ir/irText/declarations/fileWithAnnotations.kt", this::doTest);
        }

        @TestMetadata("interfaceProperties.kt")
        public void testInterfaceProperties() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/ir/irText/declarations/interfaceProperties.kt", this::doTest);
        }

        @TestMetadata("localClassWithOverrides.kt")
        public void testLocalClassWithOverrides() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/ir/irText/declarations/localClassWithOverrides.kt", this::doTest);
        }

        @TestMetadata("localDelegatedProperties.kt")
        public void testLocalDelegatedProperties() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/ir/irText/declarations/localDelegatedProperties.kt", this::doTest);
        }

        @TestMetadata("localDelegatedPropertyWithSuspendOperators.kt")
        public void testLocalDelegatedPropertyWithSuspendOperators() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/ir/irText/declarations/localDelegatedPropertyWithSuspendOperators.kt", this::doTest);
        }

        @TestMetadata("localVarInDoWhile.kt")
        public void testLocalVarInDoWhile() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/ir/irText/declarations/localVarInDoWhile.kt", this::doTest);
        }

        @TestMetadata("packageLevelProperties.kt")
        public void testPackageLevelProperties() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/ir/irText/declarations/packageLevelProperties.kt", this::doTest);
        }

        @TestMetadata("primaryCtorDefaultArguments.kt")
        public void testPrimaryCtorDefaultArguments() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/ir/irText/declarations/primaryCtorDefaultArguments.kt", this::doTest);
        }

        @TestMetadata("primaryCtorProperties.kt")
        public void testPrimaryCtorProperties() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/ir/irText/declarations/primaryCtorProperties.kt", this::doTest);
        }

        @TestMetadata("typeAlias.kt")
        public void testTypeAlias() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/ir/irText/declarations/typeAlias.kt", this::doTest);
        }

        @TestMetadata("compiler/testData/ir/irText/declarations/annotations")
        @TestDataPath("$PROJECT_ROOT")
        @RunWith(JUnit3RunnerWithInners.class)
        public static class Annotations extends AbstractIrTextTestCase {
            public void testAllFilesPresentInAnnotations() throws Exception {
                KotlinTestUtils.assertAllTestsPresentByMetadata(this.getClass(), new File("compiler/testData/ir/irText/declarations/annotations"), Pattern.compile("^(.+)\\.kt$"), TargetBackend.ANY, true);
            }

            @TestMetadata("annotationsInAnnotationArguments.kt")
            public void testAnnotationsInAnnotationArguments() throws Exception {
                KotlinTestUtils.runTest("compiler/testData/ir/irText/declarations/annotations/annotationsInAnnotationArguments.kt", this::doTest);
            }

            @TestMetadata("annotationsWithDefaultParameterValues.kt")
            public void testAnnotationsWithDefaultParameterValues() throws Exception {
                KotlinTestUtils.runTest("compiler/testData/ir/irText/declarations/annotations/annotationsWithDefaultParameterValues.kt", this::doTest);
            }

            @TestMetadata("annotationsWithVarargParameters.kt")
            public void testAnnotationsWithVarargParameters() throws Exception {
                KotlinTestUtils.runTest("compiler/testData/ir/irText/declarations/annotations/annotationsWithVarargParameters.kt", this::doTest);
            }

            @TestMetadata("arrayInAnnotationArguments.kt")
            public void testArrayInAnnotationArguments() throws Exception {
                KotlinTestUtils.runTest("compiler/testData/ir/irText/declarations/annotations/arrayInAnnotationArguments.kt", this::doTest);
            }

            @TestMetadata("classesWithAnnotations.kt")
            public void testClassesWithAnnotations() throws Exception {
                KotlinTestUtils.runTest("compiler/testData/ir/irText/declarations/annotations/classesWithAnnotations.kt", this::doTest);
            }

            @TestMetadata("constExpressionsInAnnotationArguments.kt")
            public void testConstExpressionsInAnnotationArguments() throws Exception {
                KotlinTestUtils.runTest("compiler/testData/ir/irText/declarations/annotations/constExpressionsInAnnotationArguments.kt", this::doTest);
            }

            @TestMetadata("constructorsWithAnnotations.kt")
            public void testConstructorsWithAnnotations() throws Exception {
                KotlinTestUtils.runTest("compiler/testData/ir/irText/declarations/annotations/constructorsWithAnnotations.kt", this::doTest);
            }

            @TestMetadata("delegateFieldWithAnnotations.kt")
            public void testDelegateFieldWithAnnotations() throws Exception {
                KotlinTestUtils.runTest("compiler/testData/ir/irText/declarations/annotations/delegateFieldWithAnnotations.kt", this::doTest);
            }

            @TestMetadata("delegatedPropertyAccessorsWithAnnotations.kt")
            public void testDelegatedPropertyAccessorsWithAnnotations() throws Exception {
                KotlinTestUtils.runTest("compiler/testData/ir/irText/declarations/annotations/delegatedPropertyAccessorsWithAnnotations.kt", this::doTest);
            }

            @TestMetadata("enumEntriesWithAnnotations.kt")
            public void testEnumEntriesWithAnnotations() throws Exception {
                KotlinTestUtils.runTest("compiler/testData/ir/irText/declarations/annotations/enumEntriesWithAnnotations.kt", this::doTest);
            }

            @TestMetadata("enumsInAnnotationArguments.kt")
            public void testEnumsInAnnotationArguments() throws Exception {
                KotlinTestUtils.runTest("compiler/testData/ir/irText/declarations/annotations/enumsInAnnotationArguments.kt", this::doTest);
            }

            @TestMetadata("fieldsWithAnnotations.kt")
            public void testFieldsWithAnnotations() throws Exception {
                KotlinTestUtils.runTest("compiler/testData/ir/irText/declarations/annotations/fieldsWithAnnotations.kt", this::doTest);
            }

            @TestMetadata("fileAnnotations.kt")
            public void testFileAnnotations() throws Exception {
                KotlinTestUtils.runTest("compiler/testData/ir/irText/declarations/annotations/fileAnnotations.kt", this::doTest);
            }

            @TestMetadata("functionsWithAnnotations.kt")
            public void testFunctionsWithAnnotations() throws Exception {
                KotlinTestUtils.runTest("compiler/testData/ir/irText/declarations/annotations/functionsWithAnnotations.kt", this::doTest);
            }

            @TestMetadata("localDelegatedPropertiesWithAnnotations.kt")
            public void testLocalDelegatedPropertiesWithAnnotations() throws Exception {
                KotlinTestUtils.runTest("compiler/testData/ir/irText/declarations/annotations/localDelegatedPropertiesWithAnnotations.kt", this::doTest);
            }

            @TestMetadata("multipleAnnotationsInSquareBrackets.kt")
            public void testMultipleAnnotationsInSquareBrackets() throws Exception {
                KotlinTestUtils.runTest("compiler/testData/ir/irText/declarations/annotations/multipleAnnotationsInSquareBrackets.kt", this::doTest);
            }

            @TestMetadata("primaryConstructorParameterWithAnnotations.kt")
            public void testPrimaryConstructorParameterWithAnnotations() throws Exception {
                KotlinTestUtils.runTest("compiler/testData/ir/irText/declarations/annotations/primaryConstructorParameterWithAnnotations.kt", this::doTest);
            }

            @TestMetadata("propertiesWithAnnotations.kt")
            public void testPropertiesWithAnnotations() throws Exception {
                KotlinTestUtils.runTest("compiler/testData/ir/irText/declarations/annotations/propertiesWithAnnotations.kt", this::doTest);
            }

            @TestMetadata("propertyAccessorsFromClassHeaderWithAnnotations.kt")
            public void testPropertyAccessorsFromClassHeaderWithAnnotations() throws Exception {
                KotlinTestUtils.runTest("compiler/testData/ir/irText/declarations/annotations/propertyAccessorsFromClassHeaderWithAnnotations.kt", this::doTest);
            }

            @TestMetadata("propertyAccessorsWithAnnotations.kt")
            public void testPropertyAccessorsWithAnnotations() throws Exception {
                KotlinTestUtils.runTest("compiler/testData/ir/irText/declarations/annotations/propertyAccessorsWithAnnotations.kt", this::doTest);
            }

            @TestMetadata("propertySetterParameterWithAnnotations.kt")
            public void testPropertySetterParameterWithAnnotations() throws Exception {
                KotlinTestUtils.runTest("compiler/testData/ir/irText/declarations/annotations/propertySetterParameterWithAnnotations.kt", this::doTest);
            }

            @TestMetadata("receiverParameterWithAnnotations.kt")
            public void testReceiverParameterWithAnnotations() throws Exception {
                KotlinTestUtils.runTest("compiler/testData/ir/irText/declarations/annotations/receiverParameterWithAnnotations.kt", this::doTest);
            }

            @TestMetadata("spreadOperatorInAnnotationArguments.kt")
            public void testSpreadOperatorInAnnotationArguments() throws Exception {
                KotlinTestUtils.runTest("compiler/testData/ir/irText/declarations/annotations/spreadOperatorInAnnotationArguments.kt", this::doTest);
            }

            @TestMetadata("typeAliasesWithAnnotations.kt")
            public void testTypeAliasesWithAnnotations() throws Exception {
                KotlinTestUtils.runTest("compiler/testData/ir/irText/declarations/annotations/typeAliasesWithAnnotations.kt", this::doTest);
            }

            @TestMetadata("typeParametersWithAnnotations.kt")
            public void testTypeParametersWithAnnotations() throws Exception {
                KotlinTestUtils.runTest("compiler/testData/ir/irText/declarations/annotations/typeParametersWithAnnotations.kt", this::doTest);
            }

            @TestMetadata("valueParametersWithAnnotations.kt")
            public void testValueParametersWithAnnotations() throws Exception {
                KotlinTestUtils.runTest("compiler/testData/ir/irText/declarations/annotations/valueParametersWithAnnotations.kt", this::doTest);
            }

            @TestMetadata("varargsInAnnotationArguments.kt")
            public void testVarargsInAnnotationArguments() throws Exception {
                KotlinTestUtils.runTest("compiler/testData/ir/irText/declarations/annotations/varargsInAnnotationArguments.kt", this::doTest);
            }

            @TestMetadata("variablesWithAnnotations.kt")
            public void testVariablesWithAnnotations() throws Exception {
                KotlinTestUtils.runTest("compiler/testData/ir/irText/declarations/annotations/variablesWithAnnotations.kt", this::doTest);
            }
        }

        @TestMetadata("compiler/testData/ir/irText/declarations/multiplatform")
        @TestDataPath("$PROJECT_ROOT")
        @RunWith(JUnit3RunnerWithInners.class)
        public static class Multiplatform extends AbstractIrTextTestCase {
            public void testAllFilesPresentInMultiplatform() throws Exception {
                KotlinTestUtils.assertAllTestsPresentByMetadata(this.getClass(), new File("compiler/testData/ir/irText/declarations/multiplatform"), Pattern.compile("^(.+)\\.kt$"), TargetBackend.ANY, true);
            }

            @TestMetadata("expectClassInherited.kt")
            public void testExpectClassInherited() throws Exception {
                KotlinTestUtils.runTest("compiler/testData/ir/irText/declarations/multiplatform/expectClassInherited.kt", this::doTest);
            }

            @TestMetadata("expectedEnumClass.kt")
            public void testExpectedEnumClass() throws Exception {
                KotlinTestUtils.runTest("compiler/testData/ir/irText/declarations/multiplatform/expectedEnumClass.kt", this::doTest);
            }

            @TestMetadata("expectedSealedClass.kt")
            public void testExpectedSealedClass() throws Exception {
                KotlinTestUtils.runTest("compiler/testData/ir/irText/declarations/multiplatform/expectedSealedClass.kt", this::doTest);
            }
        }

        @TestMetadata("compiler/testData/ir/irText/declarations/parameters")
        @TestDataPath("$PROJECT_ROOT")
        @RunWith(JUnit3RunnerWithInners.class)
        public static class Parameters extends AbstractIrTextTestCase {
            public void testAllFilesPresentInParameters() throws Exception {
                KotlinTestUtils.assertAllTestsPresentByMetadata(this.getClass(), new File("compiler/testData/ir/irText/declarations/parameters"), Pattern.compile("^(.+)\\.kt$"), TargetBackend.ANY, true);
            }

            @TestMetadata("class.kt")
            public void testClass() throws Exception {
                KotlinTestUtils.runTest("compiler/testData/ir/irText/declarations/parameters/class.kt", this::doTest);
            }

            @TestMetadata("constructor.kt")
            public void testConstructor() throws Exception {
                KotlinTestUtils.runTest("compiler/testData/ir/irText/declarations/parameters/constructor.kt", this::doTest);
            }

            @TestMetadata("dataClassMembers.kt")
            public void testDataClassMembers() throws Exception {
                KotlinTestUtils.runTest("compiler/testData/ir/irText/declarations/parameters/dataClassMembers.kt", this::doTest);
            }

            @TestMetadata("defaultPropertyAccessors.kt")
            public void testDefaultPropertyAccessors() throws Exception {
                KotlinTestUtils.runTest("compiler/testData/ir/irText/declarations/parameters/defaultPropertyAccessors.kt", this::doTest);
            }

            @TestMetadata("delegatedMembers.kt")
            public void testDelegatedMembers() throws Exception {
                KotlinTestUtils.runTest("compiler/testData/ir/irText/declarations/parameters/delegatedMembers.kt", this::doTest);
            }

            @TestMetadata("fun.kt")
            public void testFun() throws Exception {
                KotlinTestUtils.runTest("compiler/testData/ir/irText/declarations/parameters/fun.kt", this::doTest);
            }

            @TestMetadata("genericInnerClass.kt")
            public void testGenericInnerClass() throws Exception {
                KotlinTestUtils.runTest("compiler/testData/ir/irText/declarations/parameters/genericInnerClass.kt", this::doTest);
            }

            @TestMetadata("lambdas.kt")
            public void testLambdas() throws Exception {
                KotlinTestUtils.runTest("compiler/testData/ir/irText/declarations/parameters/lambdas.kt", this::doTest);
            }

            @TestMetadata("localFun.kt")
            public void testLocalFun() throws Exception {
                KotlinTestUtils.runTest("compiler/testData/ir/irText/declarations/parameters/localFun.kt", this::doTest);
            }

            @TestMetadata("propertyAccessors.kt")
            public void testPropertyAccessors() throws Exception {
                KotlinTestUtils.runTest("compiler/testData/ir/irText/declarations/parameters/propertyAccessors.kt", this::doTest);
            }

            @TestMetadata("typeParameterBeforeBound.kt")
            public void testTypeParameterBeforeBound() throws Exception {
                KotlinTestUtils.runTest("compiler/testData/ir/irText/declarations/parameters/typeParameterBeforeBound.kt", this::doTest);
            }

            @TestMetadata("typeParameterBoundedBySubclass.kt")
            public void testTypeParameterBoundedBySubclass() throws Exception {
                KotlinTestUtils.runTest("compiler/testData/ir/irText/declarations/parameters/typeParameterBoundedBySubclass.kt", this::doTest);
            }
        }

        @TestMetadata("compiler/testData/ir/irText/declarations/provideDelegate")
        @TestDataPath("$PROJECT_ROOT")
        @RunWith(JUnit3RunnerWithInners.class)
        public static class ProvideDelegate extends AbstractIrTextTestCase {
            public void testAllFilesPresentInProvideDelegate() throws Exception {
                KotlinTestUtils.assertAllTestsPresentByMetadata(this.getClass(), new File("compiler/testData/ir/irText/declarations/provideDelegate"), Pattern.compile("^(.+)\\.kt$"), TargetBackend.ANY, true);
            }

            @TestMetadata("differentReceivers.kt")
            public void testDifferentReceivers() throws Exception {
                KotlinTestUtils.runTest("compiler/testData/ir/irText/declarations/provideDelegate/differentReceivers.kt", this::doTest);
            }

            @TestMetadata("local.kt")
            public void testLocal() throws Exception {
                KotlinTestUtils.runTest("compiler/testData/ir/irText/declarations/provideDelegate/local.kt", this::doTest);
            }

            @TestMetadata("localDifferentReceivers.kt")
            public void testLocalDifferentReceivers() throws Exception {
                KotlinTestUtils.runTest("compiler/testData/ir/irText/declarations/provideDelegate/localDifferentReceivers.kt", this::doTest);
            }

            @TestMetadata("member.kt")
            public void testMember() throws Exception {
                KotlinTestUtils.runTest("compiler/testData/ir/irText/declarations/provideDelegate/member.kt", this::doTest);
            }

            @TestMetadata("memberExtension.kt")
            public void testMemberExtension() throws Exception {
                KotlinTestUtils.runTest("compiler/testData/ir/irText/declarations/provideDelegate/memberExtension.kt", this::doTest);
            }

            @TestMetadata("topLevel.kt")
            public void testTopLevel() throws Exception {
                KotlinTestUtils.runTest("compiler/testData/ir/irText/declarations/provideDelegate/topLevel.kt", this::doTest);
            }
        }
    }

    @TestMetadata("compiler/testData/ir/irText/errors")
    @TestDataPath("$PROJECT_ROOT")
    @RunWith(JUnit3RunnerWithInners.class)
    public static class Errors extends AbstractIrTextTestCase {
        public void testAllFilesPresentInErrors() throws Exception {
            KotlinTestUtils.assertAllTestsPresentByMetadata(this.getClass(), new File("compiler/testData/ir/irText/errors"), Pattern.compile("^(.+)\\.kt$"), TargetBackend.ANY, true);
        }

        @TestMetadata("suppressedNonPublicCall.kt")
        public void testSuppressedNonPublicCall() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/ir/irText/errors/suppressedNonPublicCall.kt", this::doTest);
        }

        @TestMetadata("unresolvedReference.kt")
        public void testUnresolvedReference() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/ir/irText/errors/unresolvedReference.kt", this::doTest);
        }
    }

    @TestMetadata("compiler/testData/ir/irText/expressions")
    @TestDataPath("$PROJECT_ROOT")
    @RunWith(JUnit3RunnerWithInners.class)
    public static class Expressions extends AbstractIrTextTestCase {
        public void testAllFilesPresentInExpressions() throws Exception {
            KotlinTestUtils.assertAllTestsPresentByMetadata(this.getClass(), new File("compiler/testData/ir/irText/expressions"), Pattern.compile("^(.+)\\.kt$"), TargetBackend.ANY, true);
        }

        @TestMetadata("argumentMappedWithError.kt")
        public void testArgumentMappedWithError() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/ir/irText/expressions/argumentMappedWithError.kt", this::doTest);
        }

        @TestMetadata("arrayAccess.kt")
        public void testArrayAccess() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/ir/irText/expressions/arrayAccess.kt", this::doTest);
        }

        @TestMetadata("arrayAssignment.kt")
        public void testArrayAssignment() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/ir/irText/expressions/arrayAssignment.kt", this::doTest);
        }

        @TestMetadata("arrayAugmentedAssignment1.kt")
        public void testArrayAugmentedAssignment1() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/ir/irText/expressions/arrayAugmentedAssignment1.kt", this::doTest);
        }

        @TestMetadata("arrayAugmentedAssignment2.kt")
        public void testArrayAugmentedAssignment2() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/ir/irText/expressions/arrayAugmentedAssignment2.kt", this::doTest);
        }

        @TestMetadata("assignments.kt")
        public void testAssignments() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/ir/irText/expressions/assignments.kt", this::doTest);
        }

        @TestMetadata("augmentedAssignment1.kt")
        public void testAugmentedAssignment1() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/ir/irText/expressions/augmentedAssignment1.kt", this::doTest);
        }

        @TestMetadata("augmentedAssignment2.kt")
        public void testAugmentedAssignment2() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/ir/irText/expressions/augmentedAssignment2.kt", this::doTest);
        }

        @TestMetadata("augmentedAssignmentWithExpression.kt")
        public void testAugmentedAssignmentWithExpression() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/ir/irText/expressions/augmentedAssignmentWithExpression.kt", this::doTest);
        }

        @TestMetadata("badBreakContinue.kt")
        public void testBadBreakContinue() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/ir/irText/expressions/badBreakContinue.kt", this::doTest);
        }

        @TestMetadata("bangbang.kt")
        public void testBangbang() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/ir/irText/expressions/bangbang.kt", this::doTest);
        }

        @TestMetadata("booleanConstsInAndAndOrOr.kt")
        public void testBooleanConstsInAndAndOrOr() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/ir/irText/expressions/booleanConstsInAndAndOrOr.kt", this::doTest);
        }

        @TestMetadata("booleanOperators.kt")
        public void testBooleanOperators() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/ir/irText/expressions/booleanOperators.kt", this::doTest);
        }

        @TestMetadata("boundCallableReferences.kt")
        public void testBoundCallableReferences() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/ir/irText/expressions/boundCallableReferences.kt", this::doTest);
        }

        @TestMetadata("boxOk.kt")
        public void testBoxOk() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/ir/irText/expressions/boxOk.kt", this::doTest);
        }

        @TestMetadata("breakContinue.kt")
        public void testBreakContinue() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/ir/irText/expressions/breakContinue.kt", this::doTest);
        }

        @TestMetadata("breakContinueInLoopHeader.kt")
        public void testBreakContinueInLoopHeader() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/ir/irText/expressions/breakContinueInLoopHeader.kt", this::doTest);
        }

        @TestMetadata("callWithReorderedArguments.kt")
        public void testCallWithReorderedArguments() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/ir/irText/expressions/callWithReorderedArguments.kt", this::doTest);
        }

        @TestMetadata("callableRefToGenericMember.kt")
        public void testCallableRefToGenericMember() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/ir/irText/expressions/callableRefToGenericMember.kt", this::doTest);
        }

        @TestMetadata("callableReferenceToImportedFromObject.kt")
        public void testCallableReferenceToImportedFromObject() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/ir/irText/expressions/callableReferenceToImportedFromObject.kt", this::doTest);
        }

        @TestMetadata("calls.kt")
        public void testCalls() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/ir/irText/expressions/calls.kt", this::doTest);
        }

        @TestMetadata("castToTypeParameter.kt")
        public void testCastToTypeParameter() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/ir/irText/expressions/castToTypeParameter.kt", this::doTest);
        }

        @TestMetadata("catchParameterAccess.kt")
        public void testCatchParameterAccess() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/ir/irText/expressions/catchParameterAccess.kt", this::doTest);
        }

        @TestMetadata("chainOfSafeCalls.kt")
        public void testChainOfSafeCalls() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/ir/irText/expressions/chainOfSafeCalls.kt", this::doTest);
        }

        @TestMetadata("classReference.kt")
        public void testClassReference() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/ir/irText/expressions/classReference.kt", this::doTest);
        }

        @TestMetadata("coercionToUnit.kt")
        public void testCoercionToUnit() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/ir/irText/expressions/coercionToUnit.kt", this::doTest);
        }

        @TestMetadata("complexAugmentedAssignment.kt")
        public void testComplexAugmentedAssignment() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/ir/irText/expressions/complexAugmentedAssignment.kt", this::doTest);
        }

        @TestMetadata("contructorCall.kt")
        public void testContructorCall() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/ir/irText/expressions/contructorCall.kt", this::doTest);
        }

        @TestMetadata("conventionComparisons.kt")
        public void testConventionComparisons() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/ir/irText/expressions/conventionComparisons.kt", this::doTest);
        }

        @TestMetadata("destructuring1.kt")
        public void testDestructuring1() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/ir/irText/expressions/destructuring1.kt", this::doTest);
        }

        @TestMetadata("destructuringWithUnderscore.kt")
        public void testDestructuringWithUnderscore() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/ir/irText/expressions/destructuringWithUnderscore.kt", this::doTest);
        }

        @TestMetadata("dotQualified.kt")
        public void testDotQualified() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/ir/irText/expressions/dotQualified.kt", this::doTest);
        }

        @TestMetadata("elvis.kt")
        public void testElvis() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/ir/irText/expressions/elvis.kt", this::doTest);
        }

        @TestMetadata("enumEntryAsReceiver.kt")
        public void testEnumEntryAsReceiver() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/ir/irText/expressions/enumEntryAsReceiver.kt", this::doTest);
        }

        @TestMetadata("equality.kt")
        public void testEquality() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/ir/irText/expressions/equality.kt", this::doTest);
        }

        @TestMetadata("extFunInvokeAsFun.kt")
        public void testExtFunInvokeAsFun() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/ir/irText/expressions/extFunInvokeAsFun.kt", this::doTest);
        }

        @TestMetadata("extFunSafeInvoke.kt")
        public void testExtFunSafeInvoke() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/ir/irText/expressions/extFunSafeInvoke.kt", this::doTest);
        }

        @TestMetadata("extensionPropertyGetterCall.kt")
        public void testExtensionPropertyGetterCall() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/ir/irText/expressions/extensionPropertyGetterCall.kt", this::doTest);
        }

        @TestMetadata("field.kt")
        public void testField() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/ir/irText/expressions/field.kt", this::doTest);
        }

        @TestMetadata("for.kt")
        public void testFor() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/ir/irText/expressions/for.kt", this::doTest);
        }

        @TestMetadata("forWithBreakContinue.kt")
        public void testForWithBreakContinue() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/ir/irText/expressions/forWithBreakContinue.kt", this::doTest);
        }

        @TestMetadata("forWithImplicitReceivers.kt")
        public void testForWithImplicitReceivers() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/ir/irText/expressions/forWithImplicitReceivers.kt", this::doTest);
        }

        @TestMetadata("funImportedFromObject.kt")
        public void testFunImportedFromObject() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/ir/irText/expressions/funImportedFromObject.kt", this::doTest);
        }

        @TestMetadata("genericPropertyCall.kt")
        public void testGenericPropertyCall() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/ir/irText/expressions/genericPropertyCall.kt", this::doTest);
        }

        @TestMetadata("identity.kt")
        public void testIdentity() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/ir/irText/expressions/identity.kt", this::doTest);
        }

        @TestMetadata("ifElseIf.kt")
        public void testIfElseIf() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/ir/irText/expressions/ifElseIf.kt", this::doTest);
        }

        @TestMetadata("implicitCastOnPlatformType.kt")
        public void testImplicitCastOnPlatformType() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/ir/irText/expressions/implicitCastOnPlatformType.kt", this::doTest);
        }

        @TestMetadata("implicitCastToTypeParameter.kt")
        public void testImplicitCastToTypeParameter() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/ir/irText/expressions/implicitCastToTypeParameter.kt", this::doTest);
        }

        @TestMetadata("in.kt")
        public void testIn() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/ir/irText/expressions/in.kt", this::doTest);
        }

        @TestMetadata("incrementDecrement.kt")
        public void testIncrementDecrement() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/ir/irText/expressions/incrementDecrement.kt", this::doTest);
        }

        @TestMetadata("interfaceThisRef.kt")
        public void testInterfaceThisRef() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/ir/irText/expressions/interfaceThisRef.kt", this::doTest);
        }

        @TestMetadata("jvmInstanceFieldReference.kt")
        public void testJvmInstanceFieldReference() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/ir/irText/expressions/jvmInstanceFieldReference.kt", this::doTest);
        }

        @TestMetadata("jvmStaticFieldReference.kt")
        public void testJvmStaticFieldReference() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/ir/irText/expressions/jvmStaticFieldReference.kt", this::doTest);
        }

        @TestMetadata("kt16904.kt")
        public void testKt16904() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/ir/irText/expressions/kt16904.kt", this::doTest);
        }

        @TestMetadata("kt16905.kt")
        public void testKt16905() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/ir/irText/expressions/kt16905.kt", this::doTest);
        }

        @TestMetadata("kt23030.kt")
        public void testKt23030() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/ir/irText/expressions/kt23030.kt", this::doTest);
        }

        @TestMetadata("lambdaInCAO.kt")
        public void testLambdaInCAO() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/ir/irText/expressions/lambdaInCAO.kt", this::doTest);
        }

        @TestMetadata("literals.kt")
        public void testLiterals() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/ir/irText/expressions/literals.kt", this::doTest);
        }

        @TestMetadata("memberTypeArguments.kt")
        public void testMemberTypeArguments() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/ir/irText/expressions/memberTypeArguments.kt", this::doTest);
        }

        @TestMetadata("membersImportedFromObject.kt")
        public void testMembersImportedFromObject() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/ir/irText/expressions/membersImportedFromObject.kt", this::doTest);
        }

        @TestMetadata("multipleThisReferences.kt")
        public void testMultipleThisReferences() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/ir/irText/expressions/multipleThisReferences.kt", this::doTest);
        }

        @TestMetadata("objectAsCallable.kt")
        public void testObjectAsCallable() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/ir/irText/expressions/objectAsCallable.kt", this::doTest);
        }

        @TestMetadata("objectClassReference.kt")
        public void testObjectClassReference() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/ir/irText/expressions/objectClassReference.kt", this::doTest);
        }

        @TestMetadata("outerClassInstanceReference.kt")
        public void testOuterClassInstanceReference() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/ir/irText/expressions/outerClassInstanceReference.kt", this::doTest);
        }

        @TestMetadata("primitiveComparisons.kt")
        public void testPrimitiveComparisons() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/ir/irText/expressions/primitiveComparisons.kt", this::doTest);
        }

        @TestMetadata("primitivesImplicitConversions.kt")
        public void testPrimitivesImplicitConversions() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/ir/irText/expressions/primitivesImplicitConversions.kt", this::doTest);
        }

        @TestMetadata("references.kt")
        public void testReferences() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/ir/irText/expressions/references.kt", this::doTest);
        }

        @TestMetadata("reflectionLiterals.kt")
        public void testReflectionLiterals() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/ir/irText/expressions/reflectionLiterals.kt", this::doTest);
        }

        @TestMetadata("safeAssignment.kt")
        public void testSafeAssignment() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/ir/irText/expressions/safeAssignment.kt", this::doTest);
        }

        @TestMetadata("safeCallWithIncrementDecrement.kt")
        public void testSafeCallWithIncrementDecrement() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/ir/irText/expressions/safeCallWithIncrementDecrement.kt", this::doTest);
        }

        @TestMetadata("safeCalls.kt")
        public void testSafeCalls() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/ir/irText/expressions/safeCalls.kt", this::doTest);
        }

        @TestMetadata("setFieldWithImplicitCast.kt")
        public void testSetFieldWithImplicitCast() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/ir/irText/expressions/setFieldWithImplicitCast.kt", this::doTest);
        }

        @TestMetadata("simpleOperators.kt")
        public void testSimpleOperators() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/ir/irText/expressions/simpleOperators.kt", this::doTest);
        }

        @TestMetadata("simpleUnaryOperators.kt")
        public void testSimpleUnaryOperators() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/ir/irText/expressions/simpleUnaryOperators.kt", this::doTest);
        }

        @TestMetadata("smartCasts.kt")
        public void testSmartCasts() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/ir/irText/expressions/smartCasts.kt", this::doTest);
        }

        @TestMetadata("smartCastsWithDestructuring.kt")
        public void testSmartCastsWithDestructuring() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/ir/irText/expressions/smartCastsWithDestructuring.kt", this::doTest);
        }

        @TestMetadata("specializedTypeAliasConstructorCall.kt")
        public void testSpecializedTypeAliasConstructorCall() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/ir/irText/expressions/specializedTypeAliasConstructorCall.kt", this::doTest);
        }

        @TestMetadata("stringComparisons.kt")
        public void testStringComparisons() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/ir/irText/expressions/stringComparisons.kt", this::doTest);
        }

        @TestMetadata("stringPlus.kt")
        public void testStringPlus() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/ir/irText/expressions/stringPlus.kt", this::doTest);
        }

        @TestMetadata("stringTemplates.kt")
        public void testStringTemplates() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/ir/irText/expressions/stringTemplates.kt", this::doTest);
        }

        @TestMetadata("thisOfGenericOuterClass.kt")
        public void testThisOfGenericOuterClass() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/ir/irText/expressions/thisOfGenericOuterClass.kt", this::doTest);
        }

        @TestMetadata("throw.kt")
        public void testThrow() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/ir/irText/expressions/throw.kt", this::doTest);
        }

        @TestMetadata("tryCatch.kt")
        public void testTryCatch() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/ir/irText/expressions/tryCatch.kt", this::doTest);
        }

        @TestMetadata("tryCatchWithImplicitCast.kt")
        public void testTryCatchWithImplicitCast() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/ir/irText/expressions/tryCatchWithImplicitCast.kt", this::doTest);
        }

        @TestMetadata("typeArguments.kt")
        public void testTypeArguments() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/ir/irText/expressions/typeArguments.kt", this::doTest);
        }

        @TestMetadata("typeOperators.kt")
        public void testTypeOperators() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/ir/irText/expressions/typeOperators.kt", this::doTest);
        }

        @TestMetadata("typeParameterClassLiteral.kt")
        public void testTypeParameterClassLiteral() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/ir/irText/expressions/typeParameterClassLiteral.kt", this::doTest);
        }

        @TestMetadata("useImportedMember.kt")
        public void testUseImportedMember() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/ir/irText/expressions/useImportedMember.kt", this::doTest);
        }

        @TestMetadata("values.kt")
        public void testValues() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/ir/irText/expressions/values.kt", this::doTest);
        }

        @TestMetadata("vararg.kt")
        public void testVararg() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/ir/irText/expressions/vararg.kt", this::doTest);
        }

        @TestMetadata("varargWithImplicitCast.kt")
        public void testVarargWithImplicitCast() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/ir/irText/expressions/varargWithImplicitCast.kt", this::doTest);
        }

        @TestMetadata("variableAsFunctionCall.kt")
        public void testVariableAsFunctionCall() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/ir/irText/expressions/variableAsFunctionCall.kt", this::doTest);
        }

        @TestMetadata("when.kt")
        public void testWhen() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/ir/irText/expressions/when.kt", this::doTest);
        }

        @TestMetadata("whenCoercedToUnit.kt")
        public void testWhenCoercedToUnit() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/ir/irText/expressions/whenCoercedToUnit.kt", this::doTest);
        }

        @TestMetadata("whenElse.kt")
        public void testWhenElse() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/ir/irText/expressions/whenElse.kt", this::doTest);
        }

        @TestMetadata("whenReturn.kt")
        public void testWhenReturn() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/ir/irText/expressions/whenReturn.kt", this::doTest);
        }

        @TestMetadata("whileDoWhile.kt")
        public void testWhileDoWhile() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/ir/irText/expressions/whileDoWhile.kt", this::doTest);
        }

        @TestMetadata("compiler/testData/ir/irText/expressions/floatingPointComparisons")
        @TestDataPath("$PROJECT_ROOT")
        @RunWith(JUnit3RunnerWithInners.class)
        public static class FloatingPointComparisons extends AbstractIrTextTestCase {
            public void testAllFilesPresentInFloatingPointComparisons() throws Exception {
                KotlinTestUtils.assertAllTestsPresentByMetadata(this.getClass(), new File("compiler/testData/ir/irText/expressions/floatingPointComparisons"), Pattern.compile("^(.+)\\.kt$"), TargetBackend.ANY, true);
            }

            @TestMetadata("comparableWithDoubleOrFloat.kt")
            public void testComparableWithDoubleOrFloat() throws Exception {
                KotlinTestUtils.runTest("compiler/testData/ir/irText/expressions/floatingPointComparisons/comparableWithDoubleOrFloat.kt", this::doTest);
            }

            @TestMetadata("eqeqRhsConditionPossiblyAffectingLhs.kt")
            public void testEqeqRhsConditionPossiblyAffectingLhs() throws Exception {
                KotlinTestUtils.runTest("compiler/testData/ir/irText/expressions/floatingPointComparisons/eqeqRhsConditionPossiblyAffectingLhs.kt", this::doTest);
            }

            @TestMetadata("floatingPointCompareTo.kt")
            public void testFloatingPointCompareTo() throws Exception {
                KotlinTestUtils.runTest("compiler/testData/ir/irText/expressions/floatingPointComparisons/floatingPointCompareTo.kt", this::doTest);
            }

            @TestMetadata("floatingPointEqeq.kt")
            public void testFloatingPointEqeq() throws Exception {
                KotlinTestUtils.runTest("compiler/testData/ir/irText/expressions/floatingPointComparisons/floatingPointEqeq.kt", this::doTest);
            }

            @TestMetadata("floatingPointEquals.kt")
            public void testFloatingPointEquals() throws Exception {
                KotlinTestUtils.runTest("compiler/testData/ir/irText/expressions/floatingPointComparisons/floatingPointEquals.kt", this::doTest);
            }

            @TestMetadata("floatingPointExcleq.kt")
            public void testFloatingPointExcleq() throws Exception {
                KotlinTestUtils.runTest("compiler/testData/ir/irText/expressions/floatingPointComparisons/floatingPointExcleq.kt", this::doTest);
            }

            @TestMetadata("floatingPointLess.kt")
            public void testFloatingPointLess() throws Exception {
                KotlinTestUtils.runTest("compiler/testData/ir/irText/expressions/floatingPointComparisons/floatingPointLess.kt", this::doTest);
            }

            @TestMetadata("nullableAnyAsIntToDouble.kt")
            public void testNullableAnyAsIntToDouble() throws Exception {
                KotlinTestUtils.runTest("compiler/testData/ir/irText/expressions/floatingPointComparisons/nullableAnyAsIntToDouble.kt", this::doTest);
            }

            @TestMetadata("nullableFloatingPointEqeq.kt")
            public void testNullableFloatingPointEqeq() throws Exception {
                KotlinTestUtils.runTest("compiler/testData/ir/irText/expressions/floatingPointComparisons/nullableFloatingPointEqeq.kt", this::doTest);
            }

            @TestMetadata("typeParameterWithPrimitiveNumericSupertype.kt")
            public void testTypeParameterWithPrimitiveNumericSupertype() throws Exception {
                KotlinTestUtils.runTest("compiler/testData/ir/irText/expressions/floatingPointComparisons/typeParameterWithPrimitiveNumericSupertype.kt", this::doTest);
            }

            @TestMetadata("whenByFloatingPoint.kt")
            public void testWhenByFloatingPoint() throws Exception {
                KotlinTestUtils.runTest("compiler/testData/ir/irText/expressions/floatingPointComparisons/whenByFloatingPoint.kt", this::doTest);
            }
        }
    }

    @TestMetadata("compiler/testData/ir/irText/lambdas")
    @TestDataPath("$PROJECT_ROOT")
    @RunWith(JUnit3RunnerWithInners.class)
    public static class Lambdas extends AbstractIrTextTestCase {
        public void testAllFilesPresentInLambdas() throws Exception {
            KotlinTestUtils.assertAllTestsPresentByMetadata(this.getClass(), new File("compiler/testData/ir/irText/lambdas"), Pattern.compile("^(.+)\\.kt$"), TargetBackend.ANY, true);
        }

        @TestMetadata("anonymousFunction.kt")
        public void testAnonymousFunction() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/ir/irText/lambdas/anonymousFunction.kt", this::doTest);
        }

        @TestMetadata("destructuringInLambda.kt")
        public void testDestructuringInLambda() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/ir/irText/lambdas/destructuringInLambda.kt", this::doTest);
        }

        @TestMetadata("extensionLambda.kt")
        public void testExtensionLambda() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/ir/irText/lambdas/extensionLambda.kt", this::doTest);
        }

        @TestMetadata("justLambda.kt")
        public void testJustLambda() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/ir/irText/lambdas/justLambda.kt", this::doTest);
        }

        @TestMetadata("localFunction.kt")
        public void testLocalFunction() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/ir/irText/lambdas/localFunction.kt", this::doTest);
        }

        @TestMetadata("multipleImplicitReceivers.kt")
        public void testMultipleImplicitReceivers() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/ir/irText/lambdas/multipleImplicitReceivers.kt", this::doTest);
        }

        @TestMetadata("nonLocalReturn.kt")
        public void testNonLocalReturn() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/ir/irText/lambdas/nonLocalReturn.kt", this::doTest);
        }

        @TestMetadata("samAdapter.kt")
        public void testSamAdapter() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/ir/irText/lambdas/samAdapter.kt", this::doTest);
        }
    }

    @TestMetadata("compiler/testData/ir/irText/regressions")
    @TestDataPath("$PROJECT_ROOT")
    @RunWith(JUnit3RunnerWithInners.class)
    public static class Regressions extends AbstractIrTextTestCase {
        public void testAllFilesPresentInRegressions() throws Exception {
            KotlinTestUtils.assertAllTestsPresentByMetadata(this.getClass(), new File("compiler/testData/ir/irText/regressions"), Pattern.compile("^(.+)\\.kt$"), TargetBackend.ANY, true);
        }

        @TestMetadata("coercionInLoop.kt")
        public void testCoercionInLoop() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/ir/irText/regressions/coercionInLoop.kt", this::doTest);
        }

        @TestMetadata("integerCoercionToT.kt")
        public void testIntegerCoercionToT() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/ir/irText/regressions/integerCoercionToT.kt", this::doTest);
        }

        @TestMetadata("typeAliasCtorForGenericClass.kt")
        public void testTypeAliasCtorForGenericClass() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/ir/irText/regressions/typeAliasCtorForGenericClass.kt", this::doTest);
        }

        @TestMetadata("compiler/testData/ir/irText/regressions/newInference")
        @TestDataPath("$PROJECT_ROOT")
        @RunWith(JUnit3RunnerWithInners.class)
        public static class NewInference extends AbstractIrTextTestCase {
            public void testAllFilesPresentInNewInference() throws Exception {
                KotlinTestUtils.assertAllTestsPresentByMetadata(this.getClass(), new File("compiler/testData/ir/irText/regressions/newInference"), Pattern.compile("^(.+)\\.kt$"), TargetBackend.ANY, true);
            }

            @TestMetadata("fixationOrder1.kt")
            public void testFixationOrder1() throws Exception {
                KotlinTestUtils.runTest("compiler/testData/ir/irText/regressions/newInference/fixationOrder1.kt", this::doTest);
            }
        }
    }

    @TestMetadata("compiler/testData/ir/irText/singletons")
    @TestDataPath("$PROJECT_ROOT")
    @RunWith(JUnit3RunnerWithInners.class)
    public static class Singletons extends AbstractIrTextTestCase {
        public void testAllFilesPresentInSingletons() throws Exception {
            KotlinTestUtils.assertAllTestsPresentByMetadata(this.getClass(), new File("compiler/testData/ir/irText/singletons"), Pattern.compile("^(.+)\\.kt$"), TargetBackend.ANY, true);
        }

        @TestMetadata("companion.kt")
        public void testCompanion() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/ir/irText/singletons/companion.kt", this::doTest);
        }

        @TestMetadata("enumEntry.kt")
        public void testEnumEntry() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/ir/irText/singletons/enumEntry.kt", this::doTest);
        }

        @TestMetadata("object.kt")
        public void testObject() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/ir/irText/singletons/object.kt", this::doTest);
        }
    }

    @TestMetadata("compiler/testData/ir/irText/stubs")
    @TestDataPath("$PROJECT_ROOT")
    @RunWith(JUnit3RunnerWithInners.class)
    public static class Stubs extends AbstractIrTextTestCase {
        public void testAllFilesPresentInStubs() throws Exception {
            KotlinTestUtils.assertAllTestsPresentByMetadata(this.getClass(), new File("compiler/testData/ir/irText/stubs"), Pattern.compile("^(.+)\\.kt$"), TargetBackend.ANY, true);
        }

        @TestMetadata("builtinMap.kt")
        public void testBuiltinMap() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/ir/irText/stubs/builtinMap.kt", this::doTest);
        }

        @TestMetadata("javaEnum.kt")
        public void testJavaEnum() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/ir/irText/stubs/javaEnum.kt", this::doTest);
        }

        @TestMetadata("javaInnerClass.kt")
        public void testJavaInnerClass() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/ir/irText/stubs/javaInnerClass.kt", this::doTest);
        }

        @TestMetadata("javaMethod.kt")
        public void testJavaMethod() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/ir/irText/stubs/javaMethod.kt", this::doTest);
        }

        @TestMetadata("javaNestedClass.kt")
        public void testJavaNestedClass() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/ir/irText/stubs/javaNestedClass.kt", this::doTest);
        }

        @TestMetadata("javaStaticMethod.kt")
        public void testJavaStaticMethod() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/ir/irText/stubs/javaStaticMethod.kt", this::doTest);
        }

        @TestMetadata("kotlinInnerClass.kt")
        public void testKotlinInnerClass() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/ir/irText/stubs/kotlinInnerClass.kt", this::doTest);
        }

        @TestMetadata("simple.kt")
        public void testSimple() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/ir/irText/stubs/simple.kt", this::doTest);
        }
    }
}
