/*
 * Copyright 2010-2018 JetBrains s.r.o. Use of this source code is governed by the Apache 2.0 license
 * that can be found in the license/LICENSE.txt file.
 */

package org.jetbrains.kotlin.cli;

import com.intellij.testFramework.TestDataPath;
import org.jetbrains.kotlin.test.JUnit3RunnerWithInners;
import org.jetbrains.kotlin.test.KotlinTestUtils;
import org.jetbrains.kotlin.test.TargetBackend;
import org.jetbrains.kotlin.test.TestMetadata;
import org.junit.runner.RunWith;

import java.io.File;
import java.util.regex.Pattern;

/** This class is generated by {@link org.jetbrains.kotlin.generators.tests.TestsPackage}. DO NOT MODIFY MANUALLY */
@SuppressWarnings("all")
@RunWith(JUnit3RunnerWithInners.class)
public class CliTestGenerated extends AbstractCliTest {
    @TestMetadata("compiler/testData/cli/jvm")
    @TestDataPath("$PROJECT_ROOT")
    @RunWith(JUnit3RunnerWithInners.class)
    public static class Jvm extends AbstractCliTest {
        public void testAllFilesPresentInJvm() throws Exception {
            KotlinTestUtils.assertAllTestsPresentByMetadata(this.getClass(), new File("compiler/testData/cli/jvm"), Pattern.compile("^(.+)\\.args$"), TargetBackend.ANY, false);
        }

        @TestMetadata("apiVersion.args")
        public void testApiVersion() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/cli/jvm/apiVersion.args", this::doJvmTest);
        }

        @TestMetadata("apiVersion1.0.args")
        public void testApiVersion1_0() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/cli/jvm/apiVersion1.0.args", this::doJvmTest);
        }

        @TestMetadata("apiVersionAndSinceNewerKotlin.args")
        public void testApiVersionAndSinceNewerKotlin() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/cli/jvm/apiVersionAndSinceNewerKotlin.args", this::doJvmTest);
        }

        @TestMetadata("apiVersionGreaterThanLanguage.args")
        public void testApiVersionGreaterThanLanguage() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/cli/jvm/apiVersionGreaterThanLanguage.args", this::doJvmTest);
        }

        @TestMetadata("apiVersionInvalid.args")
        public void testApiVersionInvalid() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/cli/jvm/apiVersionInvalid.args", this::doJvmTest);
        }

        @TestMetadata("apiVersionLessThanLanguage.args")
        public void testApiVersionLessThanLanguage() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/cli/jvm/apiVersionLessThanLanguage.args", this::doJvmTest);
        }

        @TestMetadata("argumentPassedMultipleTimes.args")
        public void testArgumentPassedMultipleTimes() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/cli/jvm/argumentPassedMultipleTimes.args", this::doJvmTest);
        }

        @TestMetadata("classAndFileClassClash.args")
        public void testClassAndFileClassClash() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/cli/jvm/classAndFileClassClash.args", this::doJvmTest);
        }

        @TestMetadata("classAndOtherFileClassClash.args")
        public void testClassAndOtherFileClassClash() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/cli/jvm/classAndOtherFileClassClash.args", this::doJvmTest);
        }

        @TestMetadata("classAndPartClash.args")
        public void testClassAndPartClash() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/cli/jvm/classAndPartClash.args", this::doJvmTest);
        }

        @TestMetadata("classAndTraitClash.args")
        public void testClassAndTraitClash() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/cli/jvm/classAndTraitClash.args", this::doJvmTest);
        }

        @TestMetadata("classpath.args")
        public void testClasspath() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/cli/jvm/classpath.args", this::doJvmTest);
        }

        @TestMetadata("compatqualDefault.args")
        public void testCompatqualDefault() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/cli/jvm/compatqualDefault.args", this::doJvmTest);
        }

        @TestMetadata("compatqualDisable.args")
        public void testCompatqualDisable() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/cli/jvm/compatqualDisable.args", this::doJvmTest);
        }

        @TestMetadata("compatqualEnable.args")
        public void testCompatqualEnable() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/cli/jvm/compatqualEnable.args", this::doJvmTest);
        }

        @TestMetadata("compatqualWrong.args")
        public void testCompatqualWrong() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/cli/jvm/compatqualWrong.args", this::doJvmTest);
        }

        @TestMetadata("conflictingOverloads.args")
        public void testConflictingOverloads() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/cli/jvm/conflictingOverloads.args", this::doJvmTest);
        }

        @TestMetadata("coroutinesEnable.args")
        public void testCoroutinesEnable() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/cli/jvm/coroutinesEnable.args", this::doJvmTest);
        }

        @TestMetadata("coroutinesError.args")
        public void testCoroutinesError() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/cli/jvm/coroutinesError.args", this::doJvmTest);
        }

        @TestMetadata("coroutinesErrorAndEnable.args")
        public void testCoroutinesErrorAndEnable() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/cli/jvm/coroutinesErrorAndEnable.args", this::doJvmTest);
        }

        @TestMetadata("coroutinesWarn.args")
        public void testCoroutinesWarn() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/cli/jvm/coroutinesWarn.args", this::doJvmTest);
        }

        @TestMetadata("diagnosticsOrder.args")
        public void testDiagnosticsOrder() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/cli/jvm/diagnosticsOrder.args", this::doJvmTest);
        }

        @TestMetadata("duplicateSources.args")
        public void testDuplicateSources() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/cli/jvm/duplicateSources.args", this::doJvmTest);
        }

        @TestMetadata("duplicateSourcesInModule.args")
        public void testDuplicateSourcesInModule() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/cli/jvm/duplicateSourcesInModule.args", this::doJvmTest);
        }

        @TestMetadata("emptySources.args")
        public void testEmptySources() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/cli/jvm/emptySources.args", this::doJvmTest);
        }

        @TestMetadata("experimentalAndUseExperimentalWithSameAnnotation.args")
        public void testExperimentalAndUseExperimentalWithSameAnnotation() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/cli/jvm/experimentalAndUseExperimentalWithSameAnnotation.args", this::doJvmTest);
        }

        @TestMetadata("experimentalDeprecated.args")
        public void testExperimentalDeprecated() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/cli/jvm/experimentalDeprecated.args", this::doJvmTest);
        }

        @TestMetadata("experimentalDeprecatedWarning.args")
        public void testExperimentalDeprecatedWarning() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/cli/jvm/experimentalDeprecatedWarning.args", this::doJvmTest);
        }

        @TestMetadata("experimentalIsNotAnnotation.args")
        public void testExperimentalIsNotAnnotation() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/cli/jvm/experimentalIsNotAnnotation.args", this::doJvmTest);
        }

        @TestMetadata("experimentalIsNotMarker.args")
        public void testExperimentalIsNotMarker() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/cli/jvm/experimentalIsNotMarker.args", this::doJvmTest);
        }

        @TestMetadata("experimentalNested.args")
        public void testExperimentalNested() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/cli/jvm/experimentalNested.args", this::doJvmTest);
        }

        @TestMetadata("experimentalRuntimeScope.args")
        public void testExperimentalRuntimeScope() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/cli/jvm/experimentalRuntimeScope.args", this::doJvmTest);
        }

        @TestMetadata("experimentalUnresolved.args")
        public void testExperimentalUnresolved() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/cli/jvm/experimentalUnresolved.args", this::doJvmTest);
        }

        @TestMetadata("extraArgumentPassedInObsoleteForm.args")
        public void testExtraArgumentPassedInObsoleteForm() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/cli/jvm/extraArgumentPassedInObsoleteForm.args", this::doJvmTest);
        }

        @TestMetadata("extraHelp.args")
        public void testExtraHelp() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/cli/jvm/extraHelp.args", this::doJvmTest);
        }

        @TestMetadata("fileClassAndMultifileClassClash.args")
        public void testFileClassAndMultifileClassClash() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/cli/jvm/fileClassAndMultifileClassClash.args", this::doJvmTest);
        }

        @TestMetadata("fileClassAndTImplClash.args")
        public void testFileClassAndTImplClash() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/cli/jvm/fileClassAndTImplClash.args", this::doJvmTest);
        }

        @TestMetadata("fileClassClashMultipleFiles.args")
        public void testFileClassClashMultipleFiles() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/cli/jvm/fileClassClashMultipleFiles.args", this::doJvmTest);
        }

        @TestMetadata("help.args")
        public void testHelp() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/cli/jvm/help.args", this::doJvmTest);
        }

        @TestMetadata("inlineCycle.args")
        public void testInlineCycle() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/cli/jvm/inlineCycle.args", this::doJvmTest);
        }

        @TestMetadata("javaSrcWrongPackage.args")
        public void testJavaSrcWrongPackage() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/cli/jvm/javaSrcWrongPackage.args", this::doJvmTest);
        }

        @TestMetadata("jdkPathDoesNotExist.args")
        public void testJdkPathDoesNotExist() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/cli/jvm/jdkPathDoesNotExist.args", this::doJvmTest);
        }

        @TestMetadata("jsr305AllIgnore.args")
        public void testJsr305AllIgnore() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/cli/jvm/jsr305AllIgnore.args", this::doJvmTest);
        }

        @TestMetadata("jsr305DefaultMigration.args")
        public void testJsr305DefaultMigration() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/cli/jvm/jsr305DefaultMigration.args", this::doJvmTest);
        }

        @TestMetadata("jsr305DeprecatedEnable.args")
        public void testJsr305DeprecatedEnable() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/cli/jvm/jsr305DeprecatedEnable.args", this::doJvmTest);
        }

        @TestMetadata("jsr305DeprecatedIgnore.args")
        public void testJsr305DeprecatedIgnore() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/cli/jvm/jsr305DeprecatedIgnore.args", this::doJvmTest);
        }

        @TestMetadata("jsr305DeprecatedWarn.args")
        public void testJsr305DeprecatedWarn() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/cli/jvm/jsr305DeprecatedWarn.args", this::doJvmTest);
        }

        @TestMetadata("jsr305FqNameIgnore.args")
        public void testJsr305FqNameIgnore() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/cli/jvm/jsr305FqNameIgnore.args", this::doJvmTest);
        }

        @TestMetadata("jsr305FqNameStrict.args")
        public void testJsr305FqNameStrict() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/cli/jvm/jsr305FqNameStrict.args", this::doJvmTest);
        }

        @TestMetadata("jsr305Ignore.args")
        public void testJsr305Ignore() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/cli/jvm/jsr305Ignore.args", this::doJvmTest);
        }

        @TestMetadata("jsr305MigrationDefault.args")
        public void testJsr305MigrationDefault() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/cli/jvm/jsr305MigrationDefault.args", this::doJvmTest);
        }

        @TestMetadata("jsr305MigrationFqNameIgnore.args")
        public void testJsr305MigrationFqNameIgnore() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/cli/jvm/jsr305MigrationFqNameIgnore.args", this::doJvmTest);
        }

        @TestMetadata("jsr305MigrationIgnore.args")
        public void testJsr305MigrationIgnore() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/cli/jvm/jsr305MigrationIgnore.args", this::doJvmTest);
        }

        @TestMetadata("jsr305MigrationWarn.args")
        public void testJsr305MigrationWarn() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/cli/jvm/jsr305MigrationWarn.args", this::doJvmTest);
        }

        @TestMetadata("jsr305NoFlag.args")
        public void testJsr305NoFlag() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/cli/jvm/jsr305NoFlag.args", this::doJvmTest);
        }

        @TestMetadata("jsr305Strict.args")
        public void testJsr305Strict() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/cli/jvm/jsr305Strict.args", this::doJvmTest);
        }

        @TestMetadata("jsr305Warn.args")
        public void testJsr305Warn() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/cli/jvm/jsr305Warn.args", this::doJvmTest);
        }

        @TestMetadata("jvm8Target.args")
        public void testJvm8Target() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/cli/jvm/jvm8Target.args", this::doJvmTest);
        }

        @TestMetadata("kotlinHomeWithoutStdlib.args")
        public void testKotlinHomeWithoutStdlib() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/cli/jvm/kotlinHomeWithoutStdlib.args", this::doJvmTest);
        }

        @TestMetadata("kotlinPackage.args")
        public void testKotlinPackage() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/cli/jvm/kotlinPackage.args", this::doJvmTest);
        }

        @TestMetadata("kt22304.args")
        public void testKt22304() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/cli/jvm/kt22304.args", this::doJvmTest);
        }

        @TestMetadata("languageVersion.args")
        public void testLanguageVersion() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/cli/jvm/languageVersion.args", this::doJvmTest);
        }

        @TestMetadata("languageVersionInvalid.args")
        public void testLanguageVersionInvalid() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/cli/jvm/languageVersionInvalid.args", this::doJvmTest);
        }

        @TestMetadata("legacySmartCastsAfterTry.args")
        public void testLegacySmartCastsAfterTry() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/cli/jvm/legacySmartCastsAfterTry.args", this::doJvmTest);
        }

        @TestMetadata("multipleTextRangesInDiagnosticsOrder.args")
        public void testMultipleTextRangesInDiagnosticsOrder() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/cli/jvm/multipleTextRangesInDiagnosticsOrder.args", this::doJvmTest);
        }

        @TestMetadata("noReflect.args")
        public void testNoReflect() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/cli/jvm/noReflect.args", this::doJvmTest);
        }

        @TestMetadata("noStdlib.args")
        public void testNoStdlib() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/cli/jvm/noStdlib.args", this::doJvmTest);
        }

        @TestMetadata("nonExistingClassPathAndAnnotationsPath.args")
        public void testNonExistingClassPathAndAnnotationsPath() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/cli/jvm/nonExistingClassPathAndAnnotationsPath.args", this::doJvmTest);
        }

        @TestMetadata("nonExistingSourcePath.args")
        public void testNonExistingSourcePath() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/cli/jvm/nonExistingSourcePath.args", this::doJvmTest);
        }

        @TestMetadata("nonLocalDisabled.args")
        public void testNonLocalDisabled() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/cli/jvm/nonLocalDisabled.args", this::doJvmTest);
        }

        @TestMetadata("nonexistentPathInModule.args")
        public void testNonexistentPathInModule() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/cli/jvm/nonexistentPathInModule.args", this::doJvmTest);
        }

        @TestMetadata("nonexistentScript.args")
        public void testNonexistentScript() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/cli/jvm/nonexistentScript.args", this::doJvmTest);
        }

        @TestMetadata("pluginSimple.args")
        public void testPluginSimple() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/cli/jvm/pluginSimple.args", this::doJvmTest);
        }

        @TestMetadata("returnAsWhenKey.args")
        public void testReturnAsWhenKey() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/cli/jvm/returnAsWhenKey.args", this::doJvmTest);
        }

        @TestMetadata("sanitized-name.clash.args")
        public void testSanitized_name_clash() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/cli/jvm/sanitized-name.clash.args", this::doJvmTest);
        }

        @TestMetadata("signatureClash.args")
        public void testSignatureClash() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/cli/jvm/signatureClash.args", this::doJvmTest);
        }

        @TestMetadata("simple.args")
        public void testSimple() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/cli/jvm/simple.args", this::doJvmTest);
        }

        @TestMetadata("singleJavaFileRoots.args")
        public void testSingleJavaFileRoots() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/cli/jvm/singleJavaFileRoots.args", this::doJvmTest);
        }

        @TestMetadata("suppressAllWarningsJvm.args")
        public void testSuppressAllWarningsJvm() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/cli/jvm/suppressAllWarningsJvm.args", this::doJvmTest);
        }

        @TestMetadata("syntheticAccessorForPropertiesSignatureClash.args")
        public void testSyntheticAccessorForPropertiesSignatureClash() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/cli/jvm/syntheticAccessorForPropertiesSignatureClash.args", this::doJvmTest);
        }

        @TestMetadata("syntheticAccessorPropertyAndFunSignatureClash.args")
        public void testSyntheticAccessorPropertyAndFunSignatureClash() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/cli/jvm/syntheticAccessorPropertyAndFunSignatureClash.args", this::doJvmTest);
        }

        @TestMetadata("syntheticAccessorSignatureClash.args")
        public void testSyntheticAccessorSignatureClash() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/cli/jvm/syntheticAccessorSignatureClash.args", this::doJvmTest);
        }

        @TestMetadata("unknownExtraFlags.args")
        public void testUnknownExtraFlags() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/cli/jvm/unknownExtraFlags.args", this::doJvmTest);
        }

        @TestMetadata("unsupportedTypeAlias.args")
        public void testUnsupportedTypeAlias() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/cli/jvm/unsupportedTypeAlias.args", this::doJvmTest);
        }

        @TestMetadata("warningJdkWithNoJdk.args")
        public void testWarningJdkWithNoJdk() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/cli/jvm/warningJdkWithNoJdk.args", this::doJvmTest);
        }

        @TestMetadata("warningsInDummy.args")
        public void testWarningsInDummy() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/cli/jvm/warningsInDummy.args", this::doJvmTest);
        }

        @TestMetadata("werror.args")
        public void testWerror() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/cli/jvm/werror.args", this::doJvmTest);
        }

        @TestMetadata("werrorWithExplicitError.args")
        public void testWerrorWithExplicitError() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/cli/jvm/werrorWithExplicitError.args", this::doJvmTest);
        }

        @TestMetadata("werrorWithNoWarn.args")
        public void testWerrorWithNoWarn() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/cli/jvm/werrorWithNoWarn.args", this::doJvmTest);
        }

        @TestMetadata("werrorWithStrongWarning.args")
        public void testWerrorWithStrongWarning() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/cli/jvm/werrorWithStrongWarning.args", this::doJvmTest);
        }

        @TestMetadata("wrongAbiVersion.args")
        public void testWrongAbiVersion() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/cli/jvm/wrongAbiVersion.args", this::doJvmTest);
        }

        @TestMetadata("wrongAbiVersionNoErrors.args")
        public void testWrongAbiVersionNoErrors() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/cli/jvm/wrongAbiVersionNoErrors.args", this::doJvmTest);
        }

        @TestMetadata("wrongArgument.args")
        public void testWrongArgument() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/cli/jvm/wrongArgument.args", this::doJvmTest);
        }

        @TestMetadata("wrongJdkPath.args")
        public void testWrongJdkPath() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/cli/jvm/wrongJdkPath.args", this::doJvmTest);
        }

        @TestMetadata("wrongJvmTargetVersion.args")
        public void testWrongJvmTargetVersion() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/cli/jvm/wrongJvmTargetVersion.args", this::doJvmTest);
        }

        @TestMetadata("wrongScriptWithDirectory.args")
        public void testWrongScriptWithDirectory() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/cli/jvm/wrongScriptWithDirectory.args", this::doJvmTest);
        }

        @TestMetadata("wrongScriptWithKtSource.args")
        public void testWrongScriptWithKtSource() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/cli/jvm/wrongScriptWithKtSource.args", this::doJvmTest);
        }

        @TestMetadata("wrongScriptWithNoSource.args")
        public void testWrongScriptWithNoSource() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/cli/jvm/wrongScriptWithNoSource.args", this::doJvmTest);
        }

        @TestMetadata("wrongXjsr305.args")
        public void testWrongXjsr305() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/cli/jvm/wrongXjsr305.args", this::doJvmTest);
        }
    }

    @TestMetadata("compiler/testData/cli/js")
    @TestDataPath("$PROJECT_ROOT")
    @RunWith(JUnit3RunnerWithInners.class)
    public static class Js extends AbstractCliTest {
        public void testAllFilesPresentInJs() throws Exception {
            KotlinTestUtils.assertAllTestsPresentByMetadata(this.getClass(), new File("compiler/testData/cli/js"), Pattern.compile("^(.+)\\.args$"), TargetBackend.ANY, false);
        }

        @TestMetadata("createMetadata.args")
        public void testCreateMetadata() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/cli/js/createMetadata.args", this::doJsTest);
        }

        @TestMetadata("emptySources.args")
        public void testEmptySources() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/cli/js/emptySources.args", this::doJsTest);
        }

        @TestMetadata("inlineCycle.args")
        public void testInlineCycle() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/cli/js/inlineCycle.args", this::doJsTest);
        }

        @TestMetadata("jsExtraHelp.args")
        public void testJsExtraHelp() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/cli/js/jsExtraHelp.args", this::doJsTest);
        }

        @TestMetadata("jsHelp.args")
        public void testJsHelp() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/cli/js/jsHelp.args", this::doJsTest);
        }

        @TestMetadata("kotlinHomeWithoutStdlib.args")
        public void testKotlinHomeWithoutStdlib() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/cli/js/kotlinHomeWithoutStdlib.args", this::doJsTest);
        }

        @TestMetadata("kotlinPackage.args")
        public void testKotlinPackage() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/cli/js/kotlinPackage.args", this::doJsTest);
        }

        @TestMetadata("languageVersion.args")
        public void testLanguageVersion() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/cli/js/languageVersion.args", this::doJsTest);
        }

        @TestMetadata("libraryDirNotFound.args")
        public void testLibraryDirNotFound() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/cli/js/libraryDirNotFound.args", this::doJsTest);
        }

        @TestMetadata("modulesWithSameNames.args")
        public void testModulesWithSameNames() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/cli/js/modulesWithSameNames.args", this::doJsTest);
        }

        @TestMetadata("modulesWithSameNamesAndFunc.args")
        public void testModulesWithSameNamesAndFunc() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/cli/js/modulesWithSameNamesAndFunc.args", this::doJsTest);
        }

        @TestMetadata("nonExistingKotlinHome.args")
        public void testNonExistingKotlinHome() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/cli/js/nonExistingKotlinHome.args", this::doJsTest);
        }

        @TestMetadata("nonExistingSourcePath.args")
        public void testNonExistingSourcePath() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/cli/js/nonExistingSourcePath.args", this::doJsTest);
        }

        @TestMetadata("notValidLibraryDir.args")
        public void testNotValidLibraryDir() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/cli/js/notValidLibraryDir.args", this::doJsTest);
        }

        @TestMetadata("outputIsDirectory.args")
        public void testOutputIsDirectory() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/cli/js/outputIsDirectory.args", this::doJsTest);
        }

        @TestMetadata("outputPostfixFileNotFound.args")
        public void testOutputPostfixFileNotFound() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/cli/js/outputPostfixFileNotFound.args", this::doJsTest);
        }

        @TestMetadata("outputPrefixFileNotFound.args")
        public void testOutputPrefixFileNotFound() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/cli/js/outputPrefixFileNotFound.args", this::doJsTest);
        }

        @TestMetadata("simple2js.args")
        public void testSimple2js() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/cli/js/simple2js.args", this::doJsTest);
        }

        @TestMetadata("sourceMap.args")
        public void testSourceMap() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/cli/js/sourceMap.args", this::doJsTest);
        }

        @TestMetadata("sourceMapCharEscape.args")
        public void testSourceMapCharEscape() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/cli/js/sourceMapCharEscape.args", this::doJsTest);
        }

        @TestMetadata("sourceMapDuplicateRelativePaths.args")
        public void testSourceMapDuplicateRelativePaths() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/cli/js/sourceMapDuplicateRelativePaths.args", this::doJsTest);
        }

        @TestMetadata("sourceMapEmbedSources.args")
        public void testSourceMapEmbedSources() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/cli/js/sourceMapEmbedSources.args", this::doJsTest);
        }

        @TestMetadata("sourceMapPrefix.args")
        public void testSourceMapPrefix() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/cli/js/sourceMapPrefix.args", this::doJsTest);
        }

        @TestMetadata("sourceMapRelativeRoot.args")
        public void testSourceMapRelativeRoot() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/cli/js/sourceMapRelativeRoot.args", this::doJsTest);
        }

        @TestMetadata("sourceMapRootAuto.args")
        public void testSourceMapRootAuto() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/cli/js/sourceMapRootAuto.args", this::doJsTest);
        }

        @TestMetadata("sourceMapRootManual.args")
        public void testSourceMapRootManual() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/cli/js/sourceMapRootManual.args", this::doJsTest);
        }

        @TestMetadata("sourceMapRootMissing.args")
        public void testSourceMapRootMissing() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/cli/js/sourceMapRootMissing.args", this::doJsTest);
        }

        @TestMetadata("sourceMapRootMultiple.args")
        public void testSourceMapRootMultiple() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/cli/js/sourceMapRootMultiple.args", this::doJsTest);
        }

        @TestMetadata("suppressAllWarningsJS.args")
        public void testSuppressAllWarningsJS() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/cli/js/suppressAllWarningsJS.args", this::doJsTest);
        }

        @TestMetadata("withFolderAsLib.args")
        public void testWithFolderAsLib() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/cli/js/withFolderAsLib.args", this::doJsTest);
        }

        @TestMetadata("withLib.args")
        public void testWithLib() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/cli/js/withLib.args", this::doJsTest);
        }

        @TestMetadata("wrongAbiVersion.args")
        public void testWrongAbiVersion() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/cli/js/wrongAbiVersion.args", this::doJsTest);
        }
    }

    @TestMetadata("compiler/testData/cli/js-dce")
    @TestDataPath("$PROJECT_ROOT")
    @RunWith(JUnit3RunnerWithInners.class)
    public static class Js_dce extends AbstractCliTest {
        public void testAllFilesPresentInJs_dce() throws Exception {
            KotlinTestUtils.assertAllTestsPresentByMetadata(this.getClass(), new File("compiler/testData/cli/js-dce"), Pattern.compile("^(.+)\\.args$"), TargetBackend.ANY, false);
        }

        @TestMetadata("dceHelp.args")
        public void testDceHelp() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/cli/js-dce/dceHelp.args", this::doJsDceTest);
        }

        @TestMetadata("emptySources.args")
        public void testEmptySources() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/cli/js-dce/emptySources.args", this::doJsDceTest);
        }

        @TestMetadata("includeDeclarations.args")
        public void testIncludeDeclarations() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/cli/js-dce/includeDeclarations.args", this::doJsDceTest);
        }

        @TestMetadata("invalidFilename.args")
        public void testInvalidFilename() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/cli/js-dce/invalidFilename.args", this::doJsDceTest);
        }

        @TestMetadata("jsExtraHelp.args")
        public void testJsExtraHelp() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/cli/js-dce/jsExtraHelp.args", this::doJsDceTest);
        }

        @TestMetadata("nonExistingSourcePath.args")
        public void testNonExistingSourcePath() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/cli/js-dce/nonExistingSourcePath.args", this::doJsDceTest);
        }

        @TestMetadata("notFile.args")
        public void testNotFile() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/cli/js-dce/notFile.args", this::doJsDceTest);
        }

        @TestMetadata("outputIsDirectory.args")
        public void testOutputIsDirectory() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/cli/js-dce/outputIsDirectory.args", this::doJsDceTest);
        }

        @TestMetadata("parseError.args")
        public void testParseError() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/cli/js-dce/parseError.args", this::doJsDceTest);
        }

        @TestMetadata("printReachability.args")
        public void testPrintReachability() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/cli/js-dce/printReachability.args", this::doJsDceTest);
        }

        @TestMetadata("simple.args")
        public void testSimple() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/cli/js-dce/simple.args", this::doJsDceTest);
        }

        @TestMetadata("withSourceMap.args")
        public void testWithSourceMap() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/cli/js-dce/withSourceMap.args", this::doJsDceTest);
        }
    }

    @TestMetadata("compiler/testData/cli/metadata")
    @TestDataPath("$PROJECT_ROOT")
    @RunWith(JUnit3RunnerWithInners.class)
    public static class Metadata extends AbstractCliTest {
        public void testAllFilesPresentInMetadata() throws Exception {
            KotlinTestUtils.assertAllTestsPresentByMetadata(this.getClass(), new File("compiler/testData/cli/metadata"), Pattern.compile("^(.+)\\.args$"), TargetBackend.ANY, false);
        }

        @TestMetadata("moduleName.args")
        public void testModuleName() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/cli/metadata/moduleName.args", this::doMetadataTest);
        }
    }
}
