/*
 * Copyright 2010-2018 JetBrains s.r.o. Use of this source code is governed by the Apache 2.0 license
 * that can be found in the license/LICENSE.txt file.
 */

package org.jetbrains.kotlin.checkers.javac;

import com.intellij.testFramework.TestDataPath;
import org.jetbrains.kotlin.test.JUnit3RunnerWithInners;
import org.jetbrains.kotlin.test.KotlinTestUtils;
import org.jetbrains.kotlin.test.TargetBackend;
import org.jetbrains.kotlin.test.TestMetadata;
import org.junit.runner.RunWith;

import java.io.File;
import java.util.regex.Pattern;

/** This class is generated by {@link org.jetbrains.kotlin.generators.tests.TestsPackage}. DO NOT MODIFY MANUALLY */
@SuppressWarnings("all")
@RunWith(JUnit3RunnerWithInners.class)
public class JavacDiagnosticsTestGenerated extends AbstractJavacDiagnosticsTest {
    @TestMetadata("compiler/testData/javac/diagnostics/tests")
    @TestDataPath("$PROJECT_ROOT")
    @RunWith(JUnit3RunnerWithInners.class)
    public static class Tests extends AbstractJavacDiagnosticsTest {
        public void testAllFilesPresentInTests() throws Exception {
            KotlinTestUtils.assertAllTestsPresentByMetadata(this.getClass(), new File("compiler/testData/javac/diagnostics/tests"), Pattern.compile("^(.+)\\.kt$"), TargetBackend.ANY, true);
        }

        @TestMetadata("Annotations.kt")
        public void testAnnotations() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/javac/diagnostics/tests/Annotations.kt", this::doTest);
        }

        @TestMetadata("compiler/testData/javac/diagnostics/tests/imports")
        @TestDataPath("$PROJECT_ROOT")
        @RunWith(JUnit3RunnerWithInners.class)
        public static class Imports extends AbstractJavacDiagnosticsTest {
            public void testAllFilesPresentInImports() throws Exception {
                KotlinTestUtils.assertAllTestsPresentByMetadata(this.getClass(), new File("compiler/testData/javac/diagnostics/tests/imports"), Pattern.compile("^(.+)\\.kt$"), TargetBackend.ANY, true);
            }

            @TestMetadata("AllUnderImportsAmbiguity.kt")
            public void testAllUnderImportsAmbiguity() throws Exception {
                KotlinTestUtils.runTest("compiler/testData/javac/diagnostics/tests/imports/AllUnderImportsAmbiguity.kt", this::doTest);
            }

            @TestMetadata("AllUnderImportsLessPriority.kt")
            public void testAllUnderImportsLessPriority() throws Exception {
                KotlinTestUtils.runTest("compiler/testData/javac/diagnostics/tests/imports/AllUnderImportsLessPriority.kt", this::doTest);
            }

            @TestMetadata("ClassImportsConflicting.kt")
            public void testClassImportsConflicting() throws Exception {
                KotlinTestUtils.runTest("compiler/testData/javac/diagnostics/tests/imports/ClassImportsConflicting.kt", this::doTest);
            }

            @TestMetadata("CurrentPackageAndAllUnderImport.kt")
            public void testCurrentPackageAndAllUnderImport() throws Exception {
                KotlinTestUtils.runTest("compiler/testData/javac/diagnostics/tests/imports/CurrentPackageAndAllUnderImport.kt", this::doTest);
            }

            @TestMetadata("CurrentPackageAndExplicitImport.kt")
            public void testCurrentPackageAndExplicitImport() throws Exception {
                KotlinTestUtils.runTest("compiler/testData/javac/diagnostics/tests/imports/CurrentPackageAndExplicitImport.kt", this::doTest);
            }

            @TestMetadata("CurrentPackageAndExplicitNestedImport.kt")
            public void testCurrentPackageAndExplicitNestedImport() throws Exception {
                KotlinTestUtils.runTest("compiler/testData/javac/diagnostics/tests/imports/CurrentPackageAndExplicitNestedImport.kt", this::doTest);
            }

            @TestMetadata("CurrentPackageAndNestedAsteriskImport.kt")
            public void testCurrentPackageAndNestedAsteriskImport() throws Exception {
                KotlinTestUtils.runTest("compiler/testData/javac/diagnostics/tests/imports/CurrentPackageAndNestedAsteriskImport.kt", this::doTest);
            }

            @TestMetadata("ImportGenericVsPackage.kt")
            public void testImportGenericVsPackage() throws Exception {
                KotlinTestUtils.runTest("compiler/testData/javac/diagnostics/tests/imports/ImportGenericVsPackage.kt", this::doTest);
            }

            @TestMetadata("ImportProtectedClass.kt")
            public void testImportProtectedClass() throws Exception {
                KotlinTestUtils.runTest("compiler/testData/javac/diagnostics/tests/imports/ImportProtectedClass.kt", this::doTest);
            }

            @TestMetadata("ImportTwoTimes.kt")
            public void testImportTwoTimes() throws Exception {
                KotlinTestUtils.runTest("compiler/testData/javac/diagnostics/tests/imports/ImportTwoTimes.kt", this::doTest);
            }

            @TestMetadata("ImportTwoTimesStar.kt")
            public void testImportTwoTimesStar() throws Exception {
                KotlinTestUtils.runTest("compiler/testData/javac/diagnostics/tests/imports/ImportTwoTimesStar.kt", this::doTest);
            }

            @TestMetadata("NestedAndTopLevelClassClash.kt")
            public void testNestedAndTopLevelClassClash() throws Exception {
                KotlinTestUtils.runTest("compiler/testData/javac/diagnostics/tests/imports/NestedAndTopLevelClassClash.kt", this::doTest);
            }

            @TestMetadata("NestedClassClash.kt")
            public void testNestedClassClash() throws Exception {
                KotlinTestUtils.runTest("compiler/testData/javac/diagnostics/tests/imports/NestedClassClash.kt", this::doTest);
            }

            @TestMetadata("PackageExplicitAndStartImport.kt")
            public void testPackageExplicitAndStartImport() throws Exception {
                KotlinTestUtils.runTest("compiler/testData/javac/diagnostics/tests/imports/PackageExplicitAndStartImport.kt", this::doTest);
            }

            @TestMetadata("PackagePrivateAndPublicNested.kt")
            public void testPackagePrivateAndPublicNested() throws Exception {
                KotlinTestUtils.runTest("compiler/testData/javac/diagnostics/tests/imports/PackagePrivateAndPublicNested.kt", this::doTest);
            }

            @TestMetadata("TopLevelClassVsPackage.kt")
            public void testTopLevelClassVsPackage() throws Exception {
                KotlinTestUtils.runTest("compiler/testData/javac/diagnostics/tests/imports/TopLevelClassVsPackage.kt", this::doTest);
            }

            @TestMetadata("TopLevelClassVsPackage2.kt")
            public void testTopLevelClassVsPackage2() throws Exception {
                KotlinTestUtils.runTest("compiler/testData/javac/diagnostics/tests/imports/TopLevelClassVsPackage2.kt", this::doTest);
            }
        }

        @TestMetadata("compiler/testData/javac/diagnostics/tests/inheritance")
        @TestDataPath("$PROJECT_ROOT")
        @RunWith(JUnit3RunnerWithInners.class)
        public static class Inheritance extends AbstractJavacDiagnosticsTest {
            public void testAllFilesPresentInInheritance() throws Exception {
                KotlinTestUtils.assertAllTestsPresentByMetadata(this.getClass(), new File("compiler/testData/javac/diagnostics/tests/inheritance"), Pattern.compile("^(.+)\\.kt$"), TargetBackend.ANY, true);
            }

            @TestMetadata("IheritanceOfInner.kt")
            public void testIheritanceOfInner() throws Exception {
                KotlinTestUtils.runTest("compiler/testData/javac/diagnostics/tests/inheritance/IheritanceOfInner.kt", this::doTest);
            }

            @TestMetadata("InheritanceAmbiguity.kt")
            public void testInheritanceAmbiguity() throws Exception {
                KotlinTestUtils.runTest("compiler/testData/javac/diagnostics/tests/inheritance/InheritanceAmbiguity.kt", this::doTest);
            }

            @TestMetadata("InheritanceAmbiguity2.kt")
            public void testInheritanceAmbiguity2() throws Exception {
                KotlinTestUtils.runTest("compiler/testData/javac/diagnostics/tests/inheritance/InheritanceAmbiguity2.kt", this::doTest);
            }

            @TestMetadata("InheritanceAmbiguity3.kt")
            public void testInheritanceAmbiguity3() throws Exception {
                KotlinTestUtils.runTest("compiler/testData/javac/diagnostics/tests/inheritance/InheritanceAmbiguity3.kt", this::doTest);
            }

            @TestMetadata("InheritanceAmbiguity4.kt")
            public void testInheritanceAmbiguity4() throws Exception {
                KotlinTestUtils.runTest("compiler/testData/javac/diagnostics/tests/inheritance/InheritanceAmbiguity4.kt", this::doTest);
            }

            @TestMetadata("InheritanceWithKotlin.kt")
            public void testInheritanceWithKotlin() throws Exception {
                KotlinTestUtils.runTest("compiler/testData/javac/diagnostics/tests/inheritance/InheritanceWithKotlin.kt", this::doTest);
            }

            @TestMetadata("InheritanceWithKotlinClasses.kt")
            public void testInheritanceWithKotlinClasses() throws Exception {
                KotlinTestUtils.runTest("compiler/testData/javac/diagnostics/tests/inheritance/InheritanceWithKotlinClasses.kt", this::doTest);
            }

            @TestMetadata("InheritedInner.kt")
            public void testInheritedInner() throws Exception {
                KotlinTestUtils.runTest("compiler/testData/javac/diagnostics/tests/inheritance/InheritedInner.kt", this::doTest);
            }

            @TestMetadata("InheritedInner2.kt")
            public void testInheritedInner2() throws Exception {
                KotlinTestUtils.runTest("compiler/testData/javac/diagnostics/tests/inheritance/InheritedInner2.kt", this::doTest);
            }

            @TestMetadata("InheritedInnerAndSupertypeWithSameName.kt")
            public void testInheritedInnerAndSupertypeWithSameName() throws Exception {
                KotlinTestUtils.runTest("compiler/testData/javac/diagnostics/tests/inheritance/InheritedInnerAndSupertypeWithSameName.kt", this::doTest);
            }

            @TestMetadata("InheritedInnerUsageInInner.kt")
            public void testInheritedInnerUsageInInner() throws Exception {
                KotlinTestUtils.runTest("compiler/testData/javac/diagnostics/tests/inheritance/InheritedInnerUsageInInner.kt", this::doTest);
            }

            @TestMetadata("InheritedKotlinInner.kt")
            public void testInheritedKotlinInner() throws Exception {
                KotlinTestUtils.runTest("compiler/testData/javac/diagnostics/tests/inheritance/InheritedKotlinInner.kt", this::doTest);
            }

            @TestMetadata("InnerAndInheritedInner.kt")
            public void testInnerAndInheritedInner() throws Exception {
                KotlinTestUtils.runTest("compiler/testData/javac/diagnostics/tests/inheritance/InnerAndInheritedInner.kt", this::doTest);
            }

            @TestMetadata("ManyInheritedClasses.kt")
            public void testManyInheritedClasses() throws Exception {
                KotlinTestUtils.runTest("compiler/testData/javac/diagnostics/tests/inheritance/ManyInheritedClasses.kt", this::doTest);
            }

            @TestMetadata("NoAmbiguity.kt")
            public void testNoAmbiguity() throws Exception {
                KotlinTestUtils.runTest("compiler/testData/javac/diagnostics/tests/inheritance/NoAmbiguity.kt", this::doTest);
            }

            @TestMetadata("NoAmbiguity2.kt")
            public void testNoAmbiguity2() throws Exception {
                KotlinTestUtils.runTest("compiler/testData/javac/diagnostics/tests/inheritance/NoAmbiguity2.kt", this::doTest);
            }

            @TestMetadata("SameInnersInSupertypeAndSupertypesSupertype.kt")
            public void testSameInnersInSupertypeAndSupertypesSupertype() throws Exception {
                KotlinTestUtils.runTest("compiler/testData/javac/diagnostics/tests/inheritance/SameInnersInSupertypeAndSupertypesSupertype.kt", this::doTest);
            }

            @TestMetadata("SuperTypeWithSameInner.kt")
            public void testSuperTypeWithSameInner() throws Exception {
                KotlinTestUtils.runTest("compiler/testData/javac/diagnostics/tests/inheritance/SuperTypeWithSameInner.kt", this::doTest);
            }

            @TestMetadata("SupertypeInnerAndTypeParameterWithSameNames.kt")
            public void testSupertypeInnerAndTypeParameterWithSameNames() throws Exception {
                KotlinTestUtils.runTest("compiler/testData/javac/diagnostics/tests/inheritance/SupertypeInnerAndTypeParameterWithSameNames.kt", this::doTest);
            }
        }

        @TestMetadata("compiler/testData/javac/diagnostics/tests/inners")
        @TestDataPath("$PROJECT_ROOT")
        @RunWith(JUnit3RunnerWithInners.class)
        public static class Inners extends AbstractJavacDiagnosticsTest {
            public void testAllFilesPresentInInners() throws Exception {
                KotlinTestUtils.assertAllTestsPresentByMetadata(this.getClass(), new File("compiler/testData/javac/diagnostics/tests/inners"), Pattern.compile("^(.+)\\.kt$"), TargetBackend.ANY, true);
            }

            @TestMetadata("ComplexCase.kt")
            public void testComplexCase() throws Exception {
                KotlinTestUtils.runTest("compiler/testData/javac/diagnostics/tests/inners/ComplexCase.kt", this::doTest);
            }

            @TestMetadata("ComplexCase2.kt")
            public void testComplexCase2() throws Exception {
                KotlinTestUtils.runTest("compiler/testData/javac/diagnostics/tests/inners/ComplexCase2.kt", this::doTest);
            }

            @TestMetadata("CurrentPackageAndInner.kt")
            public void testCurrentPackageAndInner() throws Exception {
                KotlinTestUtils.runTest("compiler/testData/javac/diagnostics/tests/inners/CurrentPackageAndInner.kt", this::doTest);
            }

            @TestMetadata("ImportThriceNestedClass.kt")
            public void testImportThriceNestedClass() throws Exception {
                KotlinTestUtils.runTest("compiler/testData/javac/diagnostics/tests/inners/ImportThriceNestedClass.kt", this::doTest);
            }

            @TestMetadata("InnerInInner.kt")
            public void testInnerInInner() throws Exception {
                KotlinTestUtils.runTest("compiler/testData/javac/diagnostics/tests/inners/InnerInInner.kt", this::doTest);
            }

            @TestMetadata("Nested.kt")
            public void testNested() throws Exception {
                KotlinTestUtils.runTest("compiler/testData/javac/diagnostics/tests/inners/Nested.kt", this::doTest);
            }

            @TestMetadata("ThriceNestedClass.kt")
            public void testThriceNestedClass() throws Exception {
                KotlinTestUtils.runTest("compiler/testData/javac/diagnostics/tests/inners/ThriceNestedClass.kt", this::doTest);
            }
        }

        @TestMetadata("compiler/testData/javac/diagnostics/tests/qualifiedExpression")
        @TestDataPath("$PROJECT_ROOT")
        @RunWith(JUnit3RunnerWithInners.class)
        public static class QualifiedExpression extends AbstractJavacDiagnosticsTest {
            public void testAllFilesPresentInQualifiedExpression() throws Exception {
                KotlinTestUtils.assertAllTestsPresentByMetadata(this.getClass(), new File("compiler/testData/javac/diagnostics/tests/qualifiedExpression"), Pattern.compile("^(.+)\\.kt$"), TargetBackend.ANY, true);
            }

            @TestMetadata("GenericClassVsPackage.kt")
            public void testGenericClassVsPackage() throws Exception {
                KotlinTestUtils.runTest("compiler/testData/javac/diagnostics/tests/qualifiedExpression/GenericClassVsPackage.kt", this::doTest);
            }

            @TestMetadata("PackageVsClass.kt")
            public void testPackageVsClass() throws Exception {
                KotlinTestUtils.runTest("compiler/testData/javac/diagnostics/tests/qualifiedExpression/PackageVsClass.kt", this::doTest);
            }

            @TestMetadata("PackageVsClass2.kt")
            public void testPackageVsClass2() throws Exception {
                KotlinTestUtils.runTest("compiler/testData/javac/diagnostics/tests/qualifiedExpression/PackageVsClass2.kt", this::doTest);
            }

            @TestMetadata("PackageVsRootClass.kt")
            public void testPackageVsRootClass() throws Exception {
                KotlinTestUtils.runTest("compiler/testData/javac/diagnostics/tests/qualifiedExpression/PackageVsRootClass.kt", this::doTest);
            }

            @TestMetadata("visibleClassVsQualifiedClass.kt")
            public void testVisibleClassVsQualifiedClass() throws Exception {
                KotlinTestUtils.runTest("compiler/testData/javac/diagnostics/tests/qualifiedExpression/visibleClassVsQualifiedClass.kt", this::doTest);
            }
        }

        @TestMetadata("compiler/testData/javac/diagnostics/tests/typeParameters")
        @TestDataPath("$PROJECT_ROOT")
        @RunWith(JUnit3RunnerWithInners.class)
        public static class TypeParameters extends AbstractJavacDiagnosticsTest {
            public void testAllFilesPresentInTypeParameters() throws Exception {
                KotlinTestUtils.assertAllTestsPresentByMetadata(this.getClass(), new File("compiler/testData/javac/diagnostics/tests/typeParameters"), Pattern.compile("^(.+)\\.kt$"), TargetBackend.ANY, true);
            }

            @TestMetadata("Clash.kt")
            public void testClash() throws Exception {
                KotlinTestUtils.runTest("compiler/testData/javac/diagnostics/tests/typeParameters/Clash.kt", this::doTest);
            }

            @TestMetadata("ComplexCase.kt")
            public void testComplexCase() throws Exception {
                KotlinTestUtils.runTest("compiler/testData/javac/diagnostics/tests/typeParameters/ComplexCase.kt", this::doTest);
            }

            @TestMetadata("InheritedInnerAndTypeParameterWithSameNames.kt")
            public void testInheritedInnerAndTypeParameterWithSameNames() throws Exception {
                KotlinTestUtils.runTest("compiler/testData/javac/diagnostics/tests/typeParameters/InheritedInnerAndTypeParameterWithSameNames.kt", this::doTest);
            }

            @TestMetadata("InnerWithTypeParameter.kt")
            public void testInnerWithTypeParameter() throws Exception {
                KotlinTestUtils.runTest("compiler/testData/javac/diagnostics/tests/typeParameters/InnerWithTypeParameter.kt", this::doTest);
            }

            @TestMetadata("NestedWithInner.kt")
            public void testNestedWithInner() throws Exception {
                KotlinTestUtils.runTest("compiler/testData/javac/diagnostics/tests/typeParameters/NestedWithInner.kt", this::doTest);
            }

            @TestMetadata("SeveralInnersWithTypeParameters.kt")
            public void testSeveralInnersWithTypeParameters() throws Exception {
                KotlinTestUtils.runTest("compiler/testData/javac/diagnostics/tests/typeParameters/SeveralInnersWithTypeParameters.kt", this::doTest);
            }

            @TestMetadata("TypeParametersInInnerAndOuterWithSameNames.kt")
            public void testTypeParametersInInnerAndOuterWithSameNames() throws Exception {
                KotlinTestUtils.runTest("compiler/testData/javac/diagnostics/tests/typeParameters/TypeParametersInInnerAndOuterWithSameNames.kt", this::doTest);
            }
        }
    }

    @TestMetadata("compiler/testData/javac/diagnostics/tests")
    @TestDataPath("$PROJECT_ROOT")
    @RunWith(JUnit3RunnerWithInners.class)
    public static class TestsWithoutJavac extends AbstractJavacDiagnosticsTest {
        public void testAllFilesPresentInTestsWithoutJavac() throws Exception {
            KotlinTestUtils.assertAllTestsPresentByMetadata(this.getClass(), new File("compiler/testData/javac/diagnostics/tests"), Pattern.compile("^(.+)\\.kt$"), TargetBackend.ANY, true);
        }

        @TestMetadata("Annotations.kt")
        public void testAnnotations() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/javac/diagnostics/tests/Annotations.kt", this::doTestWithoutJavacWrapper);
        }

        @TestMetadata("compiler/testData/javac/diagnostics/tests/imports")
        @TestDataPath("$PROJECT_ROOT")
        @RunWith(JUnit3RunnerWithInners.class)
        public static class Imports extends AbstractJavacDiagnosticsTest {
            public void testAllFilesPresentInImports() throws Exception {
                KotlinTestUtils.assertAllTestsPresentByMetadata(this.getClass(), new File("compiler/testData/javac/diagnostics/tests/imports"), Pattern.compile("^(.+)\\.kt$"), TargetBackend.ANY, true);
            }

            @TestMetadata("AllUnderImportsAmbiguity.kt")
            public void testAllUnderImportsAmbiguity() throws Exception {
                KotlinTestUtils.runTest("compiler/testData/javac/diagnostics/tests/imports/AllUnderImportsAmbiguity.kt", this::doTestWithoutJavacWrapper);
            }

            @TestMetadata("AllUnderImportsLessPriority.kt")
            public void testAllUnderImportsLessPriority() throws Exception {
                KotlinTestUtils.runTest("compiler/testData/javac/diagnostics/tests/imports/AllUnderImportsLessPriority.kt", this::doTestWithoutJavacWrapper);
            }

            @TestMetadata("ClassImportsConflicting.kt")
            public void testClassImportsConflicting() throws Exception {
                KotlinTestUtils.runTest("compiler/testData/javac/diagnostics/tests/imports/ClassImportsConflicting.kt", this::doTestWithoutJavacWrapper);
            }

            @TestMetadata("CurrentPackageAndAllUnderImport.kt")
            public void testCurrentPackageAndAllUnderImport() throws Exception {
                KotlinTestUtils.runTest("compiler/testData/javac/diagnostics/tests/imports/CurrentPackageAndAllUnderImport.kt", this::doTestWithoutJavacWrapper);
            }

            @TestMetadata("CurrentPackageAndExplicitImport.kt")
            public void testCurrentPackageAndExplicitImport() throws Exception {
                KotlinTestUtils.runTest("compiler/testData/javac/diagnostics/tests/imports/CurrentPackageAndExplicitImport.kt", this::doTestWithoutJavacWrapper);
            }

            @TestMetadata("CurrentPackageAndExplicitNestedImport.kt")
            public void testCurrentPackageAndExplicitNestedImport() throws Exception {
                KotlinTestUtils.runTest("compiler/testData/javac/diagnostics/tests/imports/CurrentPackageAndExplicitNestedImport.kt", this::doTestWithoutJavacWrapper);
            }

            @TestMetadata("CurrentPackageAndNestedAsteriskImport.kt")
            public void testCurrentPackageAndNestedAsteriskImport() throws Exception {
                KotlinTestUtils.runTest("compiler/testData/javac/diagnostics/tests/imports/CurrentPackageAndNestedAsteriskImport.kt", this::doTestWithoutJavacWrapper);
            }

            @TestMetadata("ImportGenericVsPackage.kt")
            public void testImportGenericVsPackage() throws Exception {
                KotlinTestUtils.runTest("compiler/testData/javac/diagnostics/tests/imports/ImportGenericVsPackage.kt", this::doTestWithoutJavacWrapper);
            }

            @TestMetadata("ImportProtectedClass.kt")
            public void testImportProtectedClass() throws Exception {
                KotlinTestUtils.runTest("compiler/testData/javac/diagnostics/tests/imports/ImportProtectedClass.kt", this::doTestWithoutJavacWrapper);
            }

            @TestMetadata("ImportTwoTimes.kt")
            public void testImportTwoTimes() throws Exception {
                KotlinTestUtils.runTest("compiler/testData/javac/diagnostics/tests/imports/ImportTwoTimes.kt", this::doTestWithoutJavacWrapper);
            }

            @TestMetadata("ImportTwoTimesStar.kt")
            public void testImportTwoTimesStar() throws Exception {
                KotlinTestUtils.runTest("compiler/testData/javac/diagnostics/tests/imports/ImportTwoTimesStar.kt", this::doTestWithoutJavacWrapper);
            }

            @TestMetadata("NestedAndTopLevelClassClash.kt")
            public void testNestedAndTopLevelClassClash() throws Exception {
                KotlinTestUtils.runTest("compiler/testData/javac/diagnostics/tests/imports/NestedAndTopLevelClassClash.kt", this::doTestWithoutJavacWrapper);
            }

            @TestMetadata("NestedClassClash.kt")
            public void testNestedClassClash() throws Exception {
                KotlinTestUtils.runTest("compiler/testData/javac/diagnostics/tests/imports/NestedClassClash.kt", this::doTestWithoutJavacWrapper);
            }

            @TestMetadata("PackageExplicitAndStartImport.kt")
            public void testPackageExplicitAndStartImport() throws Exception {
                KotlinTestUtils.runTest("compiler/testData/javac/diagnostics/tests/imports/PackageExplicitAndStartImport.kt", this::doTestWithoutJavacWrapper);
            }

            @TestMetadata("PackagePrivateAndPublicNested.kt")
            public void testPackagePrivateAndPublicNested() throws Exception {
                KotlinTestUtils.runTest("compiler/testData/javac/diagnostics/tests/imports/PackagePrivateAndPublicNested.kt", this::doTestWithoutJavacWrapper);
            }

            @TestMetadata("TopLevelClassVsPackage.kt")
            public void testTopLevelClassVsPackage() throws Exception {
                KotlinTestUtils.runTest("compiler/testData/javac/diagnostics/tests/imports/TopLevelClassVsPackage.kt", this::doTestWithoutJavacWrapper);
            }

            @TestMetadata("TopLevelClassVsPackage2.kt")
            public void testTopLevelClassVsPackage2() throws Exception {
                KotlinTestUtils.runTest("compiler/testData/javac/diagnostics/tests/imports/TopLevelClassVsPackage2.kt", this::doTestWithoutJavacWrapper);
            }
        }

        @TestMetadata("compiler/testData/javac/diagnostics/tests/inheritance")
        @TestDataPath("$PROJECT_ROOT")
        @RunWith(JUnit3RunnerWithInners.class)
        public static class Inheritance extends AbstractJavacDiagnosticsTest {
            public void testAllFilesPresentInInheritance() throws Exception {
                KotlinTestUtils.assertAllTestsPresentByMetadata(this.getClass(), new File("compiler/testData/javac/diagnostics/tests/inheritance"), Pattern.compile("^(.+)\\.kt$"), TargetBackend.ANY, true);
            }

            @TestMetadata("IheritanceOfInner.kt")
            public void testIheritanceOfInner() throws Exception {
                KotlinTestUtils.runTest("compiler/testData/javac/diagnostics/tests/inheritance/IheritanceOfInner.kt", this::doTestWithoutJavacWrapper);
            }

            @TestMetadata("InheritanceAmbiguity.kt")
            public void testInheritanceAmbiguity() throws Exception {
                KotlinTestUtils.runTest("compiler/testData/javac/diagnostics/tests/inheritance/InheritanceAmbiguity.kt", this::doTestWithoutJavacWrapper);
            }

            @TestMetadata("InheritanceAmbiguity2.kt")
            public void testInheritanceAmbiguity2() throws Exception {
                KotlinTestUtils.runTest("compiler/testData/javac/diagnostics/tests/inheritance/InheritanceAmbiguity2.kt", this::doTestWithoutJavacWrapper);
            }

            @TestMetadata("InheritanceAmbiguity3.kt")
            public void testInheritanceAmbiguity3() throws Exception {
                KotlinTestUtils.runTest("compiler/testData/javac/diagnostics/tests/inheritance/InheritanceAmbiguity3.kt", this::doTestWithoutJavacWrapper);
            }

            @TestMetadata("InheritanceAmbiguity4.kt")
            public void testInheritanceAmbiguity4() throws Exception {
                KotlinTestUtils.runTest("compiler/testData/javac/diagnostics/tests/inheritance/InheritanceAmbiguity4.kt", this::doTestWithoutJavacWrapper);
            }

            @TestMetadata("InheritanceWithKotlin.kt")
            public void testInheritanceWithKotlin() throws Exception {
                KotlinTestUtils.runTest("compiler/testData/javac/diagnostics/tests/inheritance/InheritanceWithKotlin.kt", this::doTestWithoutJavacWrapper);
            }

            @TestMetadata("InheritanceWithKotlinClasses.kt")
            public void testInheritanceWithKotlinClasses() throws Exception {
                KotlinTestUtils.runTest("compiler/testData/javac/diagnostics/tests/inheritance/InheritanceWithKotlinClasses.kt", this::doTestWithoutJavacWrapper);
            }

            @TestMetadata("InheritedInner.kt")
            public void testInheritedInner() throws Exception {
                KotlinTestUtils.runTest("compiler/testData/javac/diagnostics/tests/inheritance/InheritedInner.kt", this::doTestWithoutJavacWrapper);
            }

            @TestMetadata("InheritedInner2.kt")
            public void testInheritedInner2() throws Exception {
                KotlinTestUtils.runTest("compiler/testData/javac/diagnostics/tests/inheritance/InheritedInner2.kt", this::doTestWithoutJavacWrapper);
            }

            @TestMetadata("InheritedInnerAndSupertypeWithSameName.kt")
            public void testInheritedInnerAndSupertypeWithSameName() throws Exception {
                KotlinTestUtils.runTest("compiler/testData/javac/diagnostics/tests/inheritance/InheritedInnerAndSupertypeWithSameName.kt", this::doTestWithoutJavacWrapper);
            }

            @TestMetadata("InheritedInnerUsageInInner.kt")
            public void testInheritedInnerUsageInInner() throws Exception {
                KotlinTestUtils.runTest("compiler/testData/javac/diagnostics/tests/inheritance/InheritedInnerUsageInInner.kt", this::doTestWithoutJavacWrapper);
            }

            @TestMetadata("InheritedKotlinInner.kt")
            public void testInheritedKotlinInner() throws Exception {
                KotlinTestUtils.runTest("compiler/testData/javac/diagnostics/tests/inheritance/InheritedKotlinInner.kt", this::doTestWithoutJavacWrapper);
            }

            @TestMetadata("InnerAndInheritedInner.kt")
            public void testInnerAndInheritedInner() throws Exception {
                KotlinTestUtils.runTest("compiler/testData/javac/diagnostics/tests/inheritance/InnerAndInheritedInner.kt", this::doTestWithoutJavacWrapper);
            }

            @TestMetadata("ManyInheritedClasses.kt")
            public void testManyInheritedClasses() throws Exception {
                KotlinTestUtils.runTest("compiler/testData/javac/diagnostics/tests/inheritance/ManyInheritedClasses.kt", this::doTestWithoutJavacWrapper);
            }

            @TestMetadata("NoAmbiguity.kt")
            public void testNoAmbiguity() throws Exception {
                KotlinTestUtils.runTest("compiler/testData/javac/diagnostics/tests/inheritance/NoAmbiguity.kt", this::doTestWithoutJavacWrapper);
            }

            @TestMetadata("NoAmbiguity2.kt")
            public void testNoAmbiguity2() throws Exception {
                KotlinTestUtils.runTest("compiler/testData/javac/diagnostics/tests/inheritance/NoAmbiguity2.kt", this::doTestWithoutJavacWrapper);
            }

            @TestMetadata("SameInnersInSupertypeAndSupertypesSupertype.kt")
            public void testSameInnersInSupertypeAndSupertypesSupertype() throws Exception {
                KotlinTestUtils.runTest("compiler/testData/javac/diagnostics/tests/inheritance/SameInnersInSupertypeAndSupertypesSupertype.kt", this::doTestWithoutJavacWrapper);
            }

            @TestMetadata("SuperTypeWithSameInner.kt")
            public void testSuperTypeWithSameInner() throws Exception {
                KotlinTestUtils.runTest("compiler/testData/javac/diagnostics/tests/inheritance/SuperTypeWithSameInner.kt", this::doTestWithoutJavacWrapper);
            }

            @TestMetadata("SupertypeInnerAndTypeParameterWithSameNames.kt")
            public void testSupertypeInnerAndTypeParameterWithSameNames() throws Exception {
                KotlinTestUtils.runTest("compiler/testData/javac/diagnostics/tests/inheritance/SupertypeInnerAndTypeParameterWithSameNames.kt", this::doTestWithoutJavacWrapper);
            }
        }

        @TestMetadata("compiler/testData/javac/diagnostics/tests/inners")
        @TestDataPath("$PROJECT_ROOT")
        @RunWith(JUnit3RunnerWithInners.class)
        public static class Inners extends AbstractJavacDiagnosticsTest {
            public void testAllFilesPresentInInners() throws Exception {
                KotlinTestUtils.assertAllTestsPresentByMetadata(this.getClass(), new File("compiler/testData/javac/diagnostics/tests/inners"), Pattern.compile("^(.+)\\.kt$"), TargetBackend.ANY, true);
            }

            @TestMetadata("ComplexCase.kt")
            public void testComplexCase() throws Exception {
                KotlinTestUtils.runTest("compiler/testData/javac/diagnostics/tests/inners/ComplexCase.kt", this::doTestWithoutJavacWrapper);
            }

            @TestMetadata("ComplexCase2.kt")
            public void testComplexCase2() throws Exception {
                KotlinTestUtils.runTest("compiler/testData/javac/diagnostics/tests/inners/ComplexCase2.kt", this::doTestWithoutJavacWrapper);
            }

            @TestMetadata("CurrentPackageAndInner.kt")
            public void testCurrentPackageAndInner() throws Exception {
                KotlinTestUtils.runTest("compiler/testData/javac/diagnostics/tests/inners/CurrentPackageAndInner.kt", this::doTestWithoutJavacWrapper);
            }

            @TestMetadata("ImportThriceNestedClass.kt")
            public void testImportThriceNestedClass() throws Exception {
                KotlinTestUtils.runTest("compiler/testData/javac/diagnostics/tests/inners/ImportThriceNestedClass.kt", this::doTestWithoutJavacWrapper);
            }

            @TestMetadata("InnerInInner.kt")
            public void testInnerInInner() throws Exception {
                KotlinTestUtils.runTest("compiler/testData/javac/diagnostics/tests/inners/InnerInInner.kt", this::doTestWithoutJavacWrapper);
            }

            @TestMetadata("Nested.kt")
            public void testNested() throws Exception {
                KotlinTestUtils.runTest("compiler/testData/javac/diagnostics/tests/inners/Nested.kt", this::doTestWithoutJavacWrapper);
            }

            @TestMetadata("ThriceNestedClass.kt")
            public void testThriceNestedClass() throws Exception {
                KotlinTestUtils.runTest("compiler/testData/javac/diagnostics/tests/inners/ThriceNestedClass.kt", this::doTestWithoutJavacWrapper);
            }
        }

        @TestMetadata("compiler/testData/javac/diagnostics/tests/qualifiedExpression")
        @TestDataPath("$PROJECT_ROOT")
        @RunWith(JUnit3RunnerWithInners.class)
        public static class QualifiedExpression extends AbstractJavacDiagnosticsTest {
            public void testAllFilesPresentInQualifiedExpression() throws Exception {
                KotlinTestUtils.assertAllTestsPresentByMetadata(this.getClass(), new File("compiler/testData/javac/diagnostics/tests/qualifiedExpression"), Pattern.compile("^(.+)\\.kt$"), TargetBackend.ANY, true);
            }

            @TestMetadata("GenericClassVsPackage.kt")
            public void testGenericClassVsPackage() throws Exception {
                KotlinTestUtils.runTest("compiler/testData/javac/diagnostics/tests/qualifiedExpression/GenericClassVsPackage.kt", this::doTestWithoutJavacWrapper);
            }

            @TestMetadata("PackageVsClass.kt")
            public void testPackageVsClass() throws Exception {
                KotlinTestUtils.runTest("compiler/testData/javac/diagnostics/tests/qualifiedExpression/PackageVsClass.kt", this::doTestWithoutJavacWrapper);
            }

            @TestMetadata("PackageVsClass2.kt")
            public void testPackageVsClass2() throws Exception {
                KotlinTestUtils.runTest("compiler/testData/javac/diagnostics/tests/qualifiedExpression/PackageVsClass2.kt", this::doTestWithoutJavacWrapper);
            }

            @TestMetadata("PackageVsRootClass.kt")
            public void testPackageVsRootClass() throws Exception {
                KotlinTestUtils.runTest("compiler/testData/javac/diagnostics/tests/qualifiedExpression/PackageVsRootClass.kt", this::doTestWithoutJavacWrapper);
            }

            @TestMetadata("visibleClassVsQualifiedClass.kt")
            public void testVisibleClassVsQualifiedClass() throws Exception {
                KotlinTestUtils.runTest("compiler/testData/javac/diagnostics/tests/qualifiedExpression/visibleClassVsQualifiedClass.kt", this::doTestWithoutJavacWrapper);
            }
        }

        @TestMetadata("compiler/testData/javac/diagnostics/tests/typeParameters")
        @TestDataPath("$PROJECT_ROOT")
        @RunWith(JUnit3RunnerWithInners.class)
        public static class TypeParameters extends AbstractJavacDiagnosticsTest {
            public void testAllFilesPresentInTypeParameters() throws Exception {
                KotlinTestUtils.assertAllTestsPresentByMetadata(this.getClass(), new File("compiler/testData/javac/diagnostics/tests/typeParameters"), Pattern.compile("^(.+)\\.kt$"), TargetBackend.ANY, true);
            }

            @TestMetadata("Clash.kt")
            public void testClash() throws Exception {
                KotlinTestUtils.runTest("compiler/testData/javac/diagnostics/tests/typeParameters/Clash.kt", this::doTestWithoutJavacWrapper);
            }

            @TestMetadata("ComplexCase.kt")
            public void testComplexCase() throws Exception {
                KotlinTestUtils.runTest("compiler/testData/javac/diagnostics/tests/typeParameters/ComplexCase.kt", this::doTestWithoutJavacWrapper);
            }

            @TestMetadata("InheritedInnerAndTypeParameterWithSameNames.kt")
            public void testInheritedInnerAndTypeParameterWithSameNames() throws Exception {
                KotlinTestUtils.runTest("compiler/testData/javac/diagnostics/tests/typeParameters/InheritedInnerAndTypeParameterWithSameNames.kt", this::doTestWithoutJavacWrapper);
            }

            @TestMetadata("InnerWithTypeParameter.kt")
            public void testInnerWithTypeParameter() throws Exception {
                KotlinTestUtils.runTest("compiler/testData/javac/diagnostics/tests/typeParameters/InnerWithTypeParameter.kt", this::doTestWithoutJavacWrapper);
            }

            @TestMetadata("NestedWithInner.kt")
            public void testNestedWithInner() throws Exception {
                KotlinTestUtils.runTest("compiler/testData/javac/diagnostics/tests/typeParameters/NestedWithInner.kt", this::doTestWithoutJavacWrapper);
            }

            @TestMetadata("SeveralInnersWithTypeParameters.kt")
            public void testSeveralInnersWithTypeParameters() throws Exception {
                KotlinTestUtils.runTest("compiler/testData/javac/diagnostics/tests/typeParameters/SeveralInnersWithTypeParameters.kt", this::doTestWithoutJavacWrapper);
            }

            @TestMetadata("TypeParametersInInnerAndOuterWithSameNames.kt")
            public void testTypeParametersInInnerAndOuterWithSameNames() throws Exception {
                KotlinTestUtils.runTest("compiler/testData/javac/diagnostics/tests/typeParameters/TypeParametersInInnerAndOuterWithSameNames.kt", this::doTestWithoutJavacWrapper);
            }
        }
    }
}
