/*
 * Copyright 2010-2018 JetBrains s.r.o. Use of this source code is governed by the Apache 2.0 license
 * that can be found in the license/LICENSE.txt file.
 */

package org.jetbrains.kotlin.idea.debugger;

import com.intellij.testFramework.TestDataPath;
import org.jetbrains.kotlin.test.JUnit3RunnerWithInners;
import org.jetbrains.kotlin.test.KotlinTestUtils;
import org.jetbrains.kotlin.test.TargetBackend;
import org.jetbrains.kotlin.test.TestMetadata;
import org.junit.runner.RunWith;

import java.io.File;
import java.util.regex.Pattern;

/** This class is generated by {@link org.jetbrains.kotlin.generators.tests.TestsPackage}. DO NOT MODIFY MANUALLY */
@SuppressWarnings("all")
@TestMetadata("idea/testData/debugger/smartStepInto")
@TestDataPath("$PROJECT_ROOT")
@RunWith(JUnit3RunnerWithInners.class)
public class SmartStepIntoTestGenerated extends AbstractSmartStepIntoTest {
    public void testAllFilesPresentInSmartStepInto() throws Exception {
        KotlinTestUtils.assertAllTestsPresentByMetadata(this.getClass(), new File("idea/testData/debugger/smartStepInto"), Pattern.compile("^(.+)\\.kt$"), TargetBackend.ANY, true);
    }

    @TestMetadata("annotation.kt")
    public void testAnnotation() throws Exception {
        KotlinTestUtils.runTest("idea/testData/debugger/smartStepInto/annotation.kt", this::doTest);
    }

    @TestMetadata("arrayAccess.kt")
    public void testArrayAccess() throws Exception {
        KotlinTestUtils.runTest("idea/testData/debugger/smartStepInto/arrayAccess.kt", this::doTest);
    }

    @TestMetadata("callChain.kt")
    public void testCallChain() throws Exception {
        KotlinTestUtils.runTest("idea/testData/debugger/smartStepInto/callChain.kt", this::doTest);
    }

    @TestMetadata("constructor.kt")
    public void testConstructor() throws Exception {
        KotlinTestUtils.runTest("idea/testData/debugger/smartStepInto/constructor.kt", this::doTest);
    }

    @TestMetadata("conventionMethod.kt")
    public void testConventionMethod() throws Exception {
        KotlinTestUtils.runTest("idea/testData/debugger/smartStepInto/conventionMethod.kt", this::doTest);
    }

    @TestMetadata("delegatedPropertyGetter.kt")
    public void testDelegatedPropertyGetter() throws Exception {
        KotlinTestUtils.runTest("idea/testData/debugger/smartStepInto/delegatedPropertyGetter.kt", this::doTest);
    }

    @TestMetadata("doWhile.kt")
    public void testDoWhile() throws Exception {
        KotlinTestUtils.runTest("idea/testData/debugger/smartStepInto/doWhile.kt", this::doTest);
    }

    @TestMetadata("dotQualified.kt")
    public void testDotQualified() throws Exception {
        KotlinTestUtils.runTest("idea/testData/debugger/smartStepInto/dotQualified.kt", this::doTest);
    }

    @TestMetadata("dotQualifiedInParam.kt")
    public void testDotQualifiedInParam() throws Exception {
        KotlinTestUtils.runTest("idea/testData/debugger/smartStepInto/dotQualifiedInParam.kt", this::doTest);
    }

    @TestMetadata("empty.kt")
    public void testEmpty() throws Exception {
        KotlinTestUtils.runTest("idea/testData/debugger/smartStepInto/empty.kt", this::doTest);
    }

    @TestMetadata("for.kt")
    public void testFor() throws Exception {
        KotlinTestUtils.runTest("idea/testData/debugger/smartStepInto/for.kt", this::doTest);
    }

    @TestMetadata("funLiteral.kt")
    public void testFunLiteral() throws Exception {
        KotlinTestUtils.runTest("idea/testData/debugger/smartStepInto/funLiteral.kt", this::doTest);
    }

    @TestMetadata("funWithExpressionBody.kt")
    public void testFunWithExpressionBody() throws Exception {
        KotlinTestUtils.runTest("idea/testData/debugger/smartStepInto/funWithExpressionBody.kt", this::doTest);
    }

    @TestMetadata("if.kt")
    public void testIf() throws Exception {
        KotlinTestUtils.runTest("idea/testData/debugger/smartStepInto/if.kt", this::doTest);
    }

    @TestMetadata("infixCall.kt")
    public void testInfixCall() throws Exception {
        KotlinTestUtils.runTest("idea/testData/debugger/smartStepInto/infixCall.kt", this::doTest);
    }

    @TestMetadata("inlinedFunLiteral.kt")
    public void testInlinedFunLiteral() throws Exception {
        KotlinTestUtils.runTest("idea/testData/debugger/smartStepInto/inlinedFunLiteral.kt", this::doTest);
    }

    @TestMetadata("inlinedFunctionalExpression.kt")
    public void testInlinedFunctionalExpression() throws Exception {
        KotlinTestUtils.runTest("idea/testData/debugger/smartStepInto/inlinedFunctionalExpression.kt", this::doTest);
    }

    @TestMetadata("invoke.kt")
    public void testInvoke() throws Exception {
        KotlinTestUtils.runTest("idea/testData/debugger/smartStepInto/invoke.kt", this::doTest);
    }

    @TestMetadata("libraryFun.kt")
    public void testLibraryFun() throws Exception {
        KotlinTestUtils.runTest("idea/testData/debugger/smartStepInto/libraryFun.kt", this::doTest);
    }

    @TestMetadata("multiline.kt")
    public void testMultiline() throws Exception {
        KotlinTestUtils.runTest("idea/testData/debugger/smartStepInto/multiline.kt", this::doTest);
    }

    @TestMetadata("multilineCallChain.kt")
    public void testMultilineCallChain() throws Exception {
        KotlinTestUtils.runTest("idea/testData/debugger/smartStepInto/multilineCallChain.kt", this::doTest);
    }

    @TestMetadata("object.kt")
    public void testObject() throws Exception {
        KotlinTestUtils.runTest("idea/testData/debugger/smartStepInto/object.kt", this::doTest);
    }

    @TestMetadata("param.kt")
    public void testParam() throws Exception {
        KotlinTestUtils.runTest("idea/testData/debugger/smartStepInto/param.kt", this::doTest);
    }

    @TestMetadata("parantesized.kt")
    public void testParantesized() throws Exception {
        KotlinTestUtils.runTest("idea/testData/debugger/smartStepInto/parantesized.kt", this::doTest);
    }

    @TestMetadata("propertyGetter.kt")
    public void testPropertyGetter() throws Exception {
        KotlinTestUtils.runTest("idea/testData/debugger/smartStepInto/propertyGetter.kt", this::doTest);
    }

    @TestMetadata("renderer.kt")
    public void testRenderer() throws Exception {
        KotlinTestUtils.runTest("idea/testData/debugger/smartStepInto/renderer.kt", this::doTest);
    }

    @TestMetadata("simple.kt")
    public void testSimple() throws Exception {
        KotlinTestUtils.runTest("idea/testData/debugger/smartStepInto/simple.kt", this::doTest);
    }

    @TestMetadata("stringTemplate.kt")
    public void testStringTemplate() throws Exception {
        KotlinTestUtils.runTest("idea/testData/debugger/smartStepInto/stringTemplate.kt", this::doTest);
    }

    @TestMetadata("unary.kt")
    public void testUnary() throws Exception {
        KotlinTestUtils.runTest("idea/testData/debugger/smartStepInto/unary.kt", this::doTest);
    }

    @TestMetadata("when.kt")
    public void testWhen() throws Exception {
        KotlinTestUtils.runTest("idea/testData/debugger/smartStepInto/when.kt", this::doTest);
    }

    @TestMetadata("while.kt")
    public void testWhile() throws Exception {
        KotlinTestUtils.runTest("idea/testData/debugger/smartStepInto/while.kt", this::doTest);
    }
}
