/*
 * Copyright 2010-2018 JetBrains s.r.o. Use of this source code is governed by the Apache 2.0 license
 * that can be found in the license/LICENSE.txt file.
 */

package org.jetbrains.kotlin.asJava;

import com.intellij.testFramework.TestDataPath;
import org.jetbrains.kotlin.test.JUnit3RunnerWithInners;
import org.jetbrains.kotlin.test.KotlinTestUtils;
import org.jetbrains.kotlin.test.TargetBackend;
import org.jetbrains.kotlin.test.TestMetadata;
import org.junit.runner.RunWith;

import java.io.File;
import java.util.regex.Pattern;

/** This class is generated by {@link org.jetbrains.kotlin.generators.tests.TestsPackage}. DO NOT MODIFY MANUALLY */
@SuppressWarnings("all")
@TestMetadata("compiler/testData/asJava/lightClasses")
@TestDataPath("$PROJECT_ROOT")
@RunWith(JUnit3RunnerWithInners.class)
public class CompilerLightClassTestGenerated extends AbstractCompilerLightClassTest {
    public void testAllFilesPresentInLightClasses() throws Exception {
        KotlinTestUtils.assertAllTestsPresentByMetadata(this.getClass(), new File("compiler/testData/asJava/lightClasses"), Pattern.compile("^([^.]+)\\.(kt|kts)$"), TargetBackend.ANY, true, "local", "ideRegression");
    }

    @TestMetadata("AnnotationClass.kt")
    public void testAnnotationClass() throws Exception {
        KotlinTestUtils.runTest("compiler/testData/asJava/lightClasses/AnnotationClass.kt", this::doTest);
    }

    @TestMetadata("DataClassWithCustomImplementedMembers.kt")
    public void testDataClassWithCustomImplementedMembers() throws Exception {
        KotlinTestUtils.runTest("compiler/testData/asJava/lightClasses/DataClassWithCustomImplementedMembers.kt", this::doTest);
    }

    @TestMetadata("DelegatedNested.kt")
    public void testDelegatedNested() throws Exception {
        KotlinTestUtils.runTest("compiler/testData/asJava/lightClasses/DelegatedNested.kt", this::doTest);
    }

    @TestMetadata("Delegation.kt")
    public void testDelegation() throws Exception {
        KotlinTestUtils.runTest("compiler/testData/asJava/lightClasses/Delegation.kt", this::doTest);
    }

    @TestMetadata("DeprecatedEnumEntry.kt")
    public void testDeprecatedEnumEntry() throws Exception {
        KotlinTestUtils.runTest("compiler/testData/asJava/lightClasses/DeprecatedEnumEntry.kt", this::doTest);
    }

    @TestMetadata("DeprecatedNotHiddenInClass.kt")
    public void testDeprecatedNotHiddenInClass() throws Exception {
        KotlinTestUtils.runTest("compiler/testData/asJava/lightClasses/DeprecatedNotHiddenInClass.kt", this::doTest);
    }

    @TestMetadata("DollarsInName.kt")
    public void testDollarsInName() throws Exception {
        KotlinTestUtils.runTest("compiler/testData/asJava/lightClasses/DollarsInName.kt", this::doTest);
    }

    @TestMetadata("DollarsInNameNoPackage.kt")
    public void testDollarsInNameNoPackage() throws Exception {
        KotlinTestUtils.runTest("compiler/testData/asJava/lightClasses/DollarsInNameNoPackage.kt", this::doTest);
    }

    @TestMetadata("ExtendingInterfaceWithDefaultImpls.kt")
    public void testExtendingInterfaceWithDefaultImpls() throws Exception {
        KotlinTestUtils.runTest("compiler/testData/asJava/lightClasses/ExtendingInterfaceWithDefaultImpls.kt", this::doTest);
    }

    @TestMetadata("HiddenDeprecated.kt")
    public void testHiddenDeprecated() throws Exception {
        KotlinTestUtils.runTest("compiler/testData/asJava/lightClasses/HiddenDeprecated.kt", this::doTest);
    }

    @TestMetadata("HiddenDeprecatedInClass.kt")
    public void testHiddenDeprecatedInClass() throws Exception {
        KotlinTestUtils.runTest("compiler/testData/asJava/lightClasses/HiddenDeprecatedInClass.kt", this::doTest);
    }

    @TestMetadata("InheritingInterfaceDefaultImpls.kt")
    public void testInheritingInterfaceDefaultImpls() throws Exception {
        KotlinTestUtils.runTest("compiler/testData/asJava/lightClasses/InheritingInterfaceDefaultImpls.kt", this::doTest);
    }

    @TestMetadata("JvmNameOnMember.kt")
    public void testJvmNameOnMember() throws Exception {
        KotlinTestUtils.runTest("compiler/testData/asJava/lightClasses/JvmNameOnMember.kt", this::doTest);
    }

    @TestMetadata("JvmStatic.kt")
    public void testJvmStatic() throws Exception {
        KotlinTestUtils.runTest("compiler/testData/asJava/lightClasses/JvmStatic.kt", this::doTest);
    }

    @TestMetadata("NestedObjects.kt")
    public void testNestedObjects() throws Exception {
        KotlinTestUtils.runTest("compiler/testData/asJava/lightClasses/NestedObjects.kt", this::doTest);
    }

    @TestMetadata("NonDataClassWithComponentFunctions.kt")
    public void testNonDataClassWithComponentFunctions() throws Exception {
        KotlinTestUtils.runTest("compiler/testData/asJava/lightClasses/NonDataClassWithComponentFunctions.kt", this::doTest);
    }

    @TestMetadata("PublishedApi.kt")
    public void testPublishedApi() throws Exception {
        KotlinTestUtils.runTest("compiler/testData/asJava/lightClasses/PublishedApi.kt", this::doTest);
    }

    @TestMetadata("SpecialAnnotationsOnAnnotationClass.kt")
    public void testSpecialAnnotationsOnAnnotationClass() throws Exception {
        KotlinTestUtils.runTest("compiler/testData/asJava/lightClasses/SpecialAnnotationsOnAnnotationClass.kt", this::doTest);
    }

    @TestMetadata("StubOrderForOverloads.kt")
    public void testStubOrderForOverloads() throws Exception {
        KotlinTestUtils.runTest("compiler/testData/asJava/lightClasses/StubOrderForOverloads.kt", this::doTest);
    }

    @TestMetadata("VarArgs.kt")
    public void testVarArgs() throws Exception {
        KotlinTestUtils.runTest("compiler/testData/asJava/lightClasses/VarArgs.kt", this::doTest);
    }

    @TestMetadata("compiler/testData/asJava/lightClasses/compilationErrors")
    @TestDataPath("$PROJECT_ROOT")
    @RunWith(JUnit3RunnerWithInners.class)
    public static class CompilationErrors extends AbstractCompilerLightClassTest {
        @TestMetadata("ActualClass.kt")
        public void testActualClass() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/asJava/lightClasses/compilationErrors/ActualClass.kt", this::doTest);
        }

        @TestMetadata("ActualTypeAlias.kt")
        public void testActualTypeAlias() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/asJava/lightClasses/compilationErrors/ActualTypeAlias.kt", this::doTest);
        }

        @TestMetadata("ActualTypeAliasCustomJvmPackageName.kt")
        public void testActualTypeAliasCustomJvmPackageName() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/asJava/lightClasses/compilationErrors/ActualTypeAliasCustomJvmPackageName.kt", this::doTest);
        }

        public void testAllFilesPresentInCompilationErrors() throws Exception {
            KotlinTestUtils.assertAllTestsPresentByMetadata(this.getClass(), new File("compiler/testData/asJava/lightClasses/compilationErrors"), Pattern.compile("^([^.]+)\\.(kt|kts)$"), TargetBackend.ANY, true);
        }

        @TestMetadata("AllInlineOnly.kt")
        public void testAllInlineOnly() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/asJava/lightClasses/compilationErrors/AllInlineOnly.kt", this::doTest);
        }

        @TestMetadata("AnnotationModifiers.kt")
        public void testAnnotationModifiers() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/asJava/lightClasses/compilationErrors/AnnotationModifiers.kt", this::doTest);
        }

        @TestMetadata("ExpectClass.kt")
        public void testExpectClass() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/asJava/lightClasses/compilationErrors/ExpectClass.kt", this::doTest);
        }

        @TestMetadata("ExpectObject.kt")
        public void testExpectObject() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/asJava/lightClasses/compilationErrors/ExpectObject.kt", this::doTest);
        }

        @TestMetadata("ExpectedNestedClass.kt")
        public void testExpectedNestedClass() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/asJava/lightClasses/compilationErrors/ExpectedNestedClass.kt", this::doTest);
        }

        @TestMetadata("ExpectedNestedClassInObject.kt")
        public void testExpectedNestedClassInObject() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/asJava/lightClasses/compilationErrors/ExpectedNestedClassInObject.kt", this::doTest);
        }

        @TestMetadata("JvmPackageName.kt")
        public void testJvmPackageName() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/asJava/lightClasses/compilationErrors/JvmPackageName.kt", this::doTest);
        }

        @TestMetadata("PrivateInTrait.kt")
        public void testPrivateInTrait() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/asJava/lightClasses/compilationErrors/PrivateInTrait.kt", this::doTest);
        }

        @TestMetadata("RepetableAnnotations.kt")
        public void testRepetableAnnotations() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/asJava/lightClasses/compilationErrors/RepetableAnnotations.kt", this::doTest);
        }

        @TestMetadata("SameName.kt")
        public void testSameName() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/asJava/lightClasses/compilationErrors/SameName.kt", this::doTest);
        }

        @TestMetadata("TopLevelDestructuring.kt")
        public void testTopLevelDestructuring() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/asJava/lightClasses/compilationErrors/TopLevelDestructuring.kt", this::doTest);
        }

        @TestMetadata("TraitClassObjectField.kt")
        public void testTraitClassObjectField() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/asJava/lightClasses/compilationErrors/TraitClassObjectField.kt", this::doTest);
        }

        @TestMetadata("WrongAnnotations.kt")
        public void testWrongAnnotations() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/asJava/lightClasses/compilationErrors/WrongAnnotations.kt", this::doTest);
        }
    }

    @TestMetadata("compiler/testData/asJava/lightClasses/delegation")
    @TestDataPath("$PROJECT_ROOT")
    @RunWith(JUnit3RunnerWithInners.class)
    public static class Delegation extends AbstractCompilerLightClassTest {
        public void testAllFilesPresentInDelegation() throws Exception {
            KotlinTestUtils.assertAllTestsPresentByMetadata(this.getClass(), new File("compiler/testData/asJava/lightClasses/delegation"), Pattern.compile("^([^.]+)\\.(kt|kts)$"), TargetBackend.ANY, true);
        }

        @TestMetadata("Function.kt")
        public void testFunction() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/asJava/lightClasses/delegation/Function.kt", this::doTest);
        }

        @TestMetadata("Property.kt")
        public void testProperty() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/asJava/lightClasses/delegation/Property.kt", this::doTest);
        }
    }

    @TestMetadata("compiler/testData/asJava/lightClasses/facades")
    @TestDataPath("$PROJECT_ROOT")
    @RunWith(JUnit3RunnerWithInners.class)
    public static class Facades extends AbstractCompilerLightClassTest {
        public void testAllFilesPresentInFacades() throws Exception {
            KotlinTestUtils.assertAllTestsPresentByMetadata(this.getClass(), new File("compiler/testData/asJava/lightClasses/facades"), Pattern.compile("^([^.]+)\\.(kt|kts)$"), TargetBackend.ANY, true);
        }

        @TestMetadata("AllPrivate.kt")
        public void testAllPrivate() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/asJava/lightClasses/facades/AllPrivate.kt", this::doTest);
        }

        @TestMetadata("MultiFile.kt")
        public void testMultiFile() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/asJava/lightClasses/facades/MultiFile.kt", this::doTest);
        }

        @TestMetadata("SingleFile.kt")
        public void testSingleFile() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/asJava/lightClasses/facades/SingleFile.kt", this::doTest);
        }

        @TestMetadata("SingleJvmClassName.kt")
        public void testSingleJvmClassName() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/asJava/lightClasses/facades/SingleJvmClassName.kt", this::doTest);
        }
    }

    @TestMetadata("compiler/testData/asJava/lightClasses/nullabilityAnnotations")
    @TestDataPath("$PROJECT_ROOT")
    @RunWith(JUnit3RunnerWithInners.class)
    public static class NullabilityAnnotations extends AbstractCompilerLightClassTest {
        public void testAllFilesPresentInNullabilityAnnotations() throws Exception {
            KotlinTestUtils.assertAllTestsPresentByMetadata(this.getClass(), new File("compiler/testData/asJava/lightClasses/nullabilityAnnotations"), Pattern.compile("^([^.]+)\\.(kt|kts)$"), TargetBackend.ANY, true);
        }

        @TestMetadata("Class.kt")
        public void testClass() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/asJava/lightClasses/nullabilityAnnotations/Class.kt", this::doTest);
        }

        @TestMetadata("ClassObjectField.kt")
        public void testClassObjectField() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/asJava/lightClasses/nullabilityAnnotations/ClassObjectField.kt", this::doTest);
        }

        @TestMetadata("ClassWithConstructor.kt")
        public void testClassWithConstructor() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/asJava/lightClasses/nullabilityAnnotations/ClassWithConstructor.kt", this::doTest);
        }

        @TestMetadata("ClassWithConstructorAndProperties.kt")
        public void testClassWithConstructorAndProperties() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/asJava/lightClasses/nullabilityAnnotations/ClassWithConstructorAndProperties.kt", this::doTest);
        }

        @TestMetadata("FileFacade.kt")
        public void testFileFacade() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/asJava/lightClasses/nullabilityAnnotations/FileFacade.kt", this::doTest);
        }

        @TestMetadata("Generic.kt")
        public void testGeneric() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/asJava/lightClasses/nullabilityAnnotations/Generic.kt", this::doTest);
        }

        @TestMetadata("IntOverridesAny.kt")
        public void testIntOverridesAny() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/asJava/lightClasses/nullabilityAnnotations/IntOverridesAny.kt", this::doTest);
        }

        @TestMetadata("JvmOverloads.kt")
        public void testJvmOverloads() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/asJava/lightClasses/nullabilityAnnotations/JvmOverloads.kt", this::doTest);
        }

        @TestMetadata("NullableUnitReturn.kt")
        public void testNullableUnitReturn() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/asJava/lightClasses/nullabilityAnnotations/NullableUnitReturn.kt", this::doTest);
        }

        @TestMetadata("OverrideAnyWithUnit.kt")
        public void testOverrideAnyWithUnit() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/asJava/lightClasses/nullabilityAnnotations/OverrideAnyWithUnit.kt", this::doTest);
        }

        @TestMetadata("PlatformTypes.kt")
        public void testPlatformTypes() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/asJava/lightClasses/nullabilityAnnotations/PlatformTypes.kt", this::doTest);
        }

        @TestMetadata("Primitives.kt")
        public void testPrimitives() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/asJava/lightClasses/nullabilityAnnotations/Primitives.kt", this::doTest);
        }

        @TestMetadata("PrivateInClass.kt")
        public void testPrivateInClass() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/asJava/lightClasses/nullabilityAnnotations/PrivateInClass.kt", this::doTest);
        }

        @TestMetadata("Synthetic.kt")
        public void testSynthetic() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/asJava/lightClasses/nullabilityAnnotations/Synthetic.kt", this::doTest);
        }

        @TestMetadata("Trait.kt")
        public void testTrait() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/asJava/lightClasses/nullabilityAnnotations/Trait.kt", this::doTest);
        }

        @TestMetadata("UnitAsGenericArgument.kt")
        public void testUnitAsGenericArgument() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/asJava/lightClasses/nullabilityAnnotations/UnitAsGenericArgument.kt", this::doTest);
        }

        @TestMetadata("UnitParameter.kt")
        public void testUnitParameter() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/asJava/lightClasses/nullabilityAnnotations/UnitParameter.kt", this::doTest);
        }

        @TestMetadata("VoidReturn.kt")
        public void testVoidReturn() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/asJava/lightClasses/nullabilityAnnotations/VoidReturn.kt", this::doTest);
        }
    }

    @TestMetadata("compiler/testData/asJava/lightClasses/object")
    @TestDataPath("$PROJECT_ROOT")
    @RunWith(JUnit3RunnerWithInners.class)
    public static class Object extends AbstractCompilerLightClassTest {
        public void testAllFilesPresentInObject() throws Exception {
            KotlinTestUtils.assertAllTestsPresentByMetadata(this.getClass(), new File("compiler/testData/asJava/lightClasses/object"), Pattern.compile("^([^.]+)\\.(kt|kts)$"), TargetBackend.ANY, true);
        }

        @TestMetadata("SimpleObject.kt")
        public void testSimpleObject() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/asJava/lightClasses/object/SimpleObject.kt", this::doTest);
        }
    }

    @TestMetadata("compiler/testData/asJava/lightClasses/publicField")
    @TestDataPath("$PROJECT_ROOT")
    @RunWith(JUnit3RunnerWithInners.class)
    public static class PublicField extends AbstractCompilerLightClassTest {
        public void testAllFilesPresentInPublicField() throws Exception {
            KotlinTestUtils.assertAllTestsPresentByMetadata(this.getClass(), new File("compiler/testData/asJava/lightClasses/publicField"), Pattern.compile("^([^.]+)\\.(kt|kts)$"), TargetBackend.ANY, true);
        }

        @TestMetadata("CompanionObject.kt")
        public void testCompanionObject() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/asJava/lightClasses/publicField/CompanionObject.kt", this::doTest);
        }

        @TestMetadata("Simple.kt")
        public void testSimple() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/asJava/lightClasses/publicField/Simple.kt", this::doTest);
        }
    }

    @TestMetadata("compiler/testData/asJava/lightClasses/script")
    @TestDataPath("$PROJECT_ROOT")
    @RunWith(JUnit3RunnerWithInners.class)
    public static class Script extends AbstractCompilerLightClassTest {
        public void testAllFilesPresentInScript() throws Exception {
            KotlinTestUtils.assertAllTestsPresentByMetadata(this.getClass(), new File("compiler/testData/asJava/lightClasses/script"), Pattern.compile("^([^.]+)\\.(kt|kts)$"), TargetBackend.ANY, true);
        }

        @TestMetadata("HelloWorld.kts")
        public void testHelloWorld() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/asJava/lightClasses/script/HelloWorld.kts", this::doTest);
        }

        @TestMetadata("InnerClasses.kts")
        public void testInnerClasses() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/asJava/lightClasses/script/InnerClasses.kts", this::doTest);
        }
    }
}
