/*
 * Copyright 2010-2018 JetBrains s.r.o. Use of this source code is governed by the Apache 2.0 license
 * that can be found in the license/LICENSE.txt file.
 */

package org.jetbrains.kotlin.multiplatform;

import com.intellij.testFramework.TestDataPath;
import org.jetbrains.kotlin.test.JUnit3RunnerWithInners;
import org.jetbrains.kotlin.test.KotlinTestUtils;
import org.jetbrains.kotlin.test.TargetBackend;
import org.jetbrains.kotlin.test.TestMetadata;
import org.junit.runner.RunWith;

import java.io.File;
import java.util.regex.Pattern;

/** This class is generated by {@link org.jetbrains.kotlin.generators.tests.TestsPackage}. DO NOT MODIFY MANUALLY */
@SuppressWarnings("all")
@TestMetadata("compiler/testData/multiplatform")
@TestDataPath("$PROJECT_ROOT")
@RunWith(JUnit3RunnerWithInners.class)
public class MultiPlatformIntegrationTestGenerated extends AbstractMultiPlatformIntegrationTest {
    public void testAllFilesPresentInMultiplatform() throws Exception {
        KotlinTestUtils.assertAllTestsPresentByMetadata(this.getClass(), new File("compiler/testData/multiplatform"), Pattern.compile("^([^\\.]+)$"), TargetBackend.ANY, true);
    }

    @TestMetadata("compatibleProperties")
    public void testCompatibleProperties() throws Exception {
        KotlinTestUtils.runTest("compiler/testData/multiplatform/compatibleProperties/", this::doTest);
    }

    @TestMetadata("compilerArguments")
    public void testCompilerArguments() throws Exception {
        KotlinTestUtils.runTest("compiler/testData/multiplatform/compilerArguments/", this::doTest);
    }

    @TestMetadata("createImplClassInPlatformModule")
    public void testCreateImplClassInPlatformModule() throws Exception {
        KotlinTestUtils.runTest("compiler/testData/multiplatform/createImplClassInPlatformModule/", this::doTest);
    }

    @TestMetadata("explicitActualOnOverrideOfAbstractMethod")
    public void testExplicitActualOnOverrideOfAbstractMethod() throws Exception {
        KotlinTestUtils.runTest("compiler/testData/multiplatform/explicitActualOnOverrideOfAbstractMethod/", this::doTest);
    }

    @TestMetadata("genericDeclarations")
    public void testGenericDeclarations() throws Exception {
        KotlinTestUtils.runTest("compiler/testData/multiplatform/genericDeclarations/", this::doTest);
    }

    @TestMetadata("incompatibleCallables")
    public void testIncompatibleCallables() throws Exception {
        KotlinTestUtils.runTest("compiler/testData/multiplatform/incompatibleCallables/", this::doTest);
    }

    @TestMetadata("incompatibleClasses")
    public void testIncompatibleClasses() throws Exception {
        KotlinTestUtils.runTest("compiler/testData/multiplatform/incompatibleClasses/", this::doTest);
    }

    @TestMetadata("incompatibleFunctions")
    public void testIncompatibleFunctions() throws Exception {
        KotlinTestUtils.runTest("compiler/testData/multiplatform/incompatibleFunctions/", this::doTest);
    }

    @TestMetadata("incompatibleNestedClasses")
    public void testIncompatibleNestedClasses() throws Exception {
        KotlinTestUtils.runTest("compiler/testData/multiplatform/incompatibleNestedClasses/", this::doTest);
    }

    @TestMetadata("incompatibleProperties")
    public void testIncompatibleProperties() throws Exception {
        KotlinTestUtils.runTest("compiler/testData/multiplatform/incompatibleProperties/", this::doTest);
    }

    @TestMetadata("incorrectImplInClass")
    public void testIncorrectImplInClass() throws Exception {
        KotlinTestUtils.runTest("compiler/testData/multiplatform/incorrectImplInClass/", this::doTest);
    }

    @TestMetadata("jsNameClash")
    public void testJsNameClash() throws Exception {
        KotlinTestUtils.runTest("compiler/testData/multiplatform/jsNameClash/", this::doTest);
    }

    @TestMetadata("jvmMultifileClass")
    public void testJvmMultifileClass() throws Exception {
        KotlinTestUtils.runTest("compiler/testData/multiplatform/jvmMultifileClass/", this::doTest);
    }

    @TestMetadata("missingOverload")
    public void testMissingOverload() throws Exception {
        KotlinTestUtils.runTest("compiler/testData/multiplatform/missingOverload/", this::doTest);
    }

    @TestMetadata("simple")
    public void testSimple() throws Exception {
        KotlinTestUtils.runTest("compiler/testData/multiplatform/simple/", this::doTest);
    }

    @TestMetadata("simpleNoImplKeywordOnTopLevelFunction")
    public void testSimpleNoImplKeywordOnTopLevelFunction() throws Exception {
        KotlinTestUtils.runTest("compiler/testData/multiplatform/simpleNoImplKeywordOnTopLevelFunction/", this::doTest);
    }

    @TestMetadata("weakIncompatibilityWithoutActualModifier")
    public void testWeakIncompatibilityWithoutActualModifier() throws Exception {
        KotlinTestUtils.runTest("compiler/testData/multiplatform/weakIncompatibilityWithoutActualModifier/", this::doTest);
    }

    @TestMetadata("compiler/testData/multiplatform/classScopes")
    @TestDataPath("$PROJECT_ROOT")
    @RunWith(JUnit3RunnerWithInners.class)
    public static class ClassScopes extends AbstractMultiPlatformIntegrationTest {
        public void testAllFilesPresentInClassScopes() throws Exception {
            KotlinTestUtils.assertAllTestsPresentByMetadata(this.getClass(), new File("compiler/testData/multiplatform/classScopes"), Pattern.compile("^([^\\.]+)$"), TargetBackend.ANY, true);
        }

        @TestMetadata("constructorIncorrectSignature")
        public void testConstructorIncorrectSignature() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/multiplatform/classScopes/constructorIncorrectSignature/", this::doTest);
        }

        @TestMetadata("enumsWithDifferentEntries")
        public void testEnumsWithDifferentEntries() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/multiplatform/classScopes/enumsWithDifferentEntries/", this::doTest);
        }

        @TestMetadata("fakeOverrides")
        public void testFakeOverrides() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/multiplatform/classScopes/fakeOverrides/", this::doTest);
        }

        @TestMetadata("functionAndPropertyWithSameName")
        public void testFunctionAndPropertyWithSameName() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/multiplatform/classScopes/functionAndPropertyWithSameName/", this::doTest);
        }

        @TestMetadata("functionIncorrectSignature")
        public void testFunctionIncorrectSignature() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/multiplatform/classScopes/functionIncorrectSignature/", this::doTest);
        }

        @TestMetadata("functionIncorrectSignatureFromSuperclass")
        public void testFunctionIncorrectSignatureFromSuperclass() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/multiplatform/classScopes/functionIncorrectSignatureFromSuperclass/", this::doTest);
        }

        @TestMetadata("missingConstructor")
        public void testMissingConstructor() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/multiplatform/classScopes/missingConstructor/", this::doTest);
        }

        @TestMetadata("missingFunction")
        public void testMissingFunction() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/multiplatform/classScopes/missingFunction/", this::doTest);
        }

        @TestMetadata("simple")
        public void testSimple() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/multiplatform/classScopes/simple/", this::doTest);
        }
    }

    @TestMetadata("compiler/testData/multiplatform/defaultArguments")
    @TestDataPath("$PROJECT_ROOT")
    @RunWith(JUnit3RunnerWithInners.class)
    public static class DefaultArguments extends AbstractMultiPlatformIntegrationTest {
        public void testAllFilesPresentInDefaultArguments() throws Exception {
            KotlinTestUtils.assertAllTestsPresentByMetadata(this.getClass(), new File("compiler/testData/multiplatform/defaultArguments"), Pattern.compile("^([^\\.]+)$"), TargetBackend.ANY, true);
        }

        @TestMetadata("useDefaultArgumentsInDependency")
        public void testUseDefaultArgumentsInDependency() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/multiplatform/defaultArguments/useDefaultArgumentsInDependency/", this::doTest);
        }
    }

    @TestMetadata("compiler/testData/multiplatform/implTypeAlias")
    @TestDataPath("$PROJECT_ROOT")
    @RunWith(JUnit3RunnerWithInners.class)
    public static class ImplTypeAlias extends AbstractMultiPlatformIntegrationTest {
        public void testAllFilesPresentInImplTypeAlias() throws Exception {
            KotlinTestUtils.assertAllTestsPresentByMetadata(this.getClass(), new File("compiler/testData/multiplatform/implTypeAlias"), Pattern.compile("^([^\\.]+)$"), TargetBackend.ANY, true);
        }

        @TestMetadata("discriminateHeaderClassInFavorOfTypeAlias")
        public void testDiscriminateHeaderClassInFavorOfTypeAlias() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/multiplatform/implTypeAlias/discriminateHeaderClassInFavorOfTypeAlias/", this::doTest);
        }

        @TestMetadata("generic")
        public void testGeneric() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/multiplatform/implTypeAlias/generic/", this::doTest);
        }

        @TestMetadata("nestedClassesViaTypeAlias")
        public void testNestedClassesViaTypeAlias() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/multiplatform/implTypeAlias/nestedClassesViaTypeAlias/", this::doTest);
        }
    }

    @TestMetadata("compiler/testData/multiplatform/regressions")
    @TestDataPath("$PROJECT_ROOT")
    @RunWith(JUnit3RunnerWithInners.class)
    public static class Regressions extends AbstractMultiPlatformIntegrationTest {
        public void testAllFilesPresentInRegressions() throws Exception {
            KotlinTestUtils.assertAllTestsPresentByMetadata(this.getClass(), new File("compiler/testData/multiplatform/regressions"), Pattern.compile("^([^\\.]+)$"), TargetBackend.ANY, true);
        }

        @TestMetadata("incompatibleClassScopesWithImplTypeAlias")
        public void testIncompatibleClassScopesWithImplTypeAlias() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/multiplatform/regressions/incompatibleClassScopesWithImplTypeAlias/", this::doTest);
        }

        @TestMetadata("kt17001")
        public void testKt17001() throws Exception {
            KotlinTestUtils.runTest("compiler/testData/multiplatform/regressions/kt17001/", this::doTest);
        }
    }
}
