/*
 * Copyright 2010-2018 JetBrains s.r.o. Use of this source code is governed by the Apache 2.0 license
 * that can be found in the license/LICENSE.txt file.
 */

package org.jetbrains.kotlin.renderer;

import com.intellij.testFramework.TestDataPath;
import org.jetbrains.kotlin.test.JUnit3RunnerWithInners;
import org.jetbrains.kotlin.test.KotlinTestUtils;
import org.jetbrains.kotlin.test.TargetBackend;
import org.jetbrains.kotlin.test.TestMetadata;
import org.junit.runner.RunWith;

import java.io.File;
import java.util.regex.Pattern;

/** This class is generated by {@link org.jetbrains.kotlin.generators.tests.TestsPackage}. DO NOT MODIFY MANUALLY */
@SuppressWarnings("all")
@TestMetadata("compiler/testData/renderer")
@TestDataPath("$PROJECT_ROOT")
@RunWith(JUnit3RunnerWithInners.class)
public class DescriptorRendererTestGenerated extends AbstractDescriptorRendererTest {
    public void testAllFilesPresentInRenderer() throws Exception {
        KotlinTestUtils.assertAllTestsPresentByMetadata(this.getClass(), new File("compiler/testData/renderer"), Pattern.compile("^(.+)\\.kt$"), TargetBackend.ANY, true);
    }

    @TestMetadata("Classes.kt")
    public void testClasses() throws Exception {
        KotlinTestUtils.runTest("compiler/testData/renderer/Classes.kt", this::doTest);
    }

    @TestMetadata("Enum.kt")
    public void testEnum() throws Exception {
        KotlinTestUtils.runTest("compiler/testData/renderer/Enum.kt", this::doTest);
    }

    @TestMetadata("ErrorType.kt")
    public void testErrorType() throws Exception {
        KotlinTestUtils.runTest("compiler/testData/renderer/ErrorType.kt", this::doTest);
    }

    @TestMetadata("FunctionTypes.kt")
    public void testFunctionTypes() throws Exception {
        KotlinTestUtils.runTest("compiler/testData/renderer/FunctionTypes.kt", this::doTest);
    }

    @TestMetadata("FunctionTypesInSignature.kt")
    public void testFunctionTypesInSignature() throws Exception {
        KotlinTestUtils.runTest("compiler/testData/renderer/FunctionTypesInSignature.kt", this::doTest);
    }

    @TestMetadata("GlobalFunctions.kt")
    public void testGlobalFunctions() throws Exception {
        KotlinTestUtils.runTest("compiler/testData/renderer/GlobalFunctions.kt", this::doTest);
    }

    @TestMetadata("GlobalProperties.kt")
    public void testGlobalProperties() throws Exception {
        KotlinTestUtils.runTest("compiler/testData/renderer/GlobalProperties.kt", this::doTest);
    }

    @TestMetadata("InheritedMembersVisibility.kt")
    public void testInheritedMembersVisibility() throws Exception {
        KotlinTestUtils.runTest("compiler/testData/renderer/InheritedMembersVisibility.kt", this::doTest);
    }

    @TestMetadata("KeywordsInNames.kt")
    public void testKeywordsInNames() throws Exception {
        KotlinTestUtils.runTest("compiler/testData/renderer/KeywordsInNames.kt", this::doTest);
    }

    @TestMetadata("ObjectWithConstructor.kt")
    public void testObjectWithConstructor() throws Exception {
        KotlinTestUtils.runTest("compiler/testData/renderer/ObjectWithConstructor.kt", this::doTest);
    }

    @TestMetadata("StarProjection.kt")
    public void testStarProjection() throws Exception {
        KotlinTestUtils.runTest("compiler/testData/renderer/StarProjection.kt", this::doTest);
    }

    @TestMetadata("TraitWithConstructor.kt")
    public void testTraitWithConstructor() throws Exception {
        KotlinTestUtils.runTest("compiler/testData/renderer/TraitWithConstructor.kt", this::doTest);
    }

    @TestMetadata("TypeAnnotations.kt")
    public void testTypeAnnotations() throws Exception {
        KotlinTestUtils.runTest("compiler/testData/renderer/TypeAnnotations.kt", this::doTest);
    }

    @TestMetadata("UnitType.kt")
    public void testUnitType() throws Exception {
        KotlinTestUtils.runTest("compiler/testData/renderer/UnitType.kt", this::doTest);
    }
}
